# Imports

In [19]:
from nltk.translate.bleu_score import sentence_bleu
from langchain.llms import OpenAI
from langchain import PromptTemplate, SagemakerEndpoint
from langchain.llms.sagemaker_endpoint import LLMContentHandler
from langchain.chains.question_answering import load_qa_chain
from langchain.chains.summarize import load_summarize_chain

from langchain.document_loaders import TextLoader
from langchain.document_loaders.csv_loader import CSVLoader
from langchain.document_loaders import JSONLoader
from langchain.document_loaders import PyPDFLoader

from langchain.docstore.document import Document
from langchain.text_splitter import CharacterTextSplitter
from langchain.chains import RetrievalQA
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import Chroma
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.chains import VectorDBQA
from rouge_score import rouge_scorer

from langchain import OpenAI, PromptTemplate, LLMChain
from langchain.chains.mapreduce import MapReduceChain
from langchain.prompts import PromptTemplate
from langchain.embeddings.sentence_transformer import SentenceTransformerEmbeddings
from langchain.vectorstores import Chroma

import json
from pathlib import Path
from pprint import pprint
import os
from glob import glob
import requests
import urllib

import pandas as pd
import numpy as np
import csv
from metapub import PubMedFetcher

2023-07-23 22:20:38 ip-172-31-64-95 metapub.config[29969] WARNING NCBI_API_KEY was not set.

In [1]:
import sys

sys.path.append("/home/ubuntu/work/therapeutic_accelerator/custom_packages/utils")
sys.path.append("/home/ubuntu/work/therapeutic_accelerator/custom_packages/database")

In [2]:
# import functions from a file stored in a different directory
import db_tools
from utils import import_config


config, keys = import_config()

engine = db_tools.db_connection(config["database"]["host"], keys["postgres"])

# Load Data

In [ ]:
# Retreive Full Text from Table
table_name = "fulltext"

query = f""" 
    SELECT empty, corpusid, text, id FROM {table_name} LIMIT 10;
    """

full_text = db_tools.query_to_df(db_tools.query_db(engine, query))
full_text.head()

  empty   corpusid                                               text  id
0  1410  250929149  \nOPEN ACCESS EDITED BY\n\n\nAlexander Nikolae...   1
1  1411  215793097  \n\n\n\nCi Song \nState Key Laboratory of Repr...   2
2  1412  246020601  \nCOVID-19 and the Otolaryngology Residency Ma...   3
3  1413   18163935  \nAnalysis of biophysical and functional conse...   4
4  1414  237935836  \nImpact of Plant-Based Meat Alternatives on t...   5

In [ ]:
# Retreive Abstracts from Table
table_name = "abstracts_encodings"

sql = f""" 
    SELECT * FROM {table_name} LIMIT 10; 
    """

abstract_text = db_tools.query_to_df(db_tools.query_db(engine, query))

abstract_text.head()

  empty   corpusid                                               text  id
0  1410  250929149  \nOPEN ACCESS EDITED BY\n\n\nAlexander Nikolae...   1
1  1411  215793097  \n\n\n\nCi Song \nState Key Laboratory of Repr...   2
2  1412  246020601  \nCOVID-19 and the Otolaryngology Residency Ma...   3
3  1413   18163935  \nAnalysis of biophysical and functional conse...   4
4  1414  237935836  \nImpact of Plant-Based Meat Alternatives on t...   5

In [4]:
import chromaDB as cDBc
from db_tools import db_connection
from utils import import_config

config, keys = import_config()

# Chroma setup
chroma_server_host = "52.23.195.129"
chroma_client = cDBc.create_chroma_client(chroma_server_host)

# Working Collection
collection = chroma_client.get_or_create_collection("specter_abstracts")

collection.count()

2023-07-26 08:44:07.068106: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-26 08:44:08.024089: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

KeyboardInterrupt:

In [ ]:
# vector_em <=> (select vector_em from abstract_encodings_test4 where vector_em is not null limit 1) as sim
# ALTER TABLE abstract_encodings_test4 ADD COLUMN vector_em vector(768);
# psql --host=database-1.cuaho2dof33c.us-east-1.rds.amazonaws.com --port=5432 --username=postgres --password --dbname=postgres

In [8]:
# Connect to the chroma_client DB
abstract_store = chroma_client.get_collection(name="specter_abstracts")
lang_collect = chroma_client.get_collection(name="fulltext")
lang_collect.peek()

{'ids': ['220647965-0',
  '220647965-1',
  '220647965-2',
  '220647965-3',
  '220647965-4',
  '220647965-5',
  '20044380-0',
  '20044380-1',
  '20044380-2',
  '20044380-3'],
 'embeddings': [[-0.005119905341416597,
   -0.07151228189468384,
   -0.11324868351221085,
   -0.09201928228139877,
   0.00045634983689524233,
   -0.024387119337916374,
   0.028379959985613823,
   0.04509858414530754,
   0.05559356138110161,
   0.012055506929755211,
   -0.009709623642265797,
   0.02123657427728176,
   -0.0021696484182029963,
   0.08374569565057755,
   -0.05272151529788971,
   0.11446069180965424,
   0.011344498954713345,
   0.009295452386140823,
   -0.04702450707554817,
   0.0028786389157176018,
   -0.03945611044764519,
   0.03999094292521477,
   0.11128133535385132,
   0.043151360005140305,
   -0.07247650623321533,
   0.007482609245926142,
   0.009368007071316242,
   0.054855529218912125,
   -0.04732478782534599,
   -0.06813782453536987,
   0.08444996178150177,
   0.04073921591043472,
   -0.03744032606482506,
   -0.05311126261949539,
   -0.020215507596731186,
   -0.0006251035956665874,
   -0.09467754513025284,
   0.027652250602841377,
   0.03385273739695549,
   -0.05787116289138794,
   -0.0011094070505350828,
   -0.03742683306336403,
   -0.022017724812030792,
   0.016742000356316566,
   0.02952498383820057,
   -0.12797077000141144,
   -0.08032695949077606,
   -0.05143599584698677,
   0.07123086601495743,
   0.06003155559301376,
   -0.07456756383180618,
   0.027782410383224487,
   -0.01605100743472576,
   0.02990124560892582,
   -0.05412716791033745,
   -0.035381536930799484,
   -0.06878578662872314,
   -0.028757641091942787,
   -0.014204716309905052,
   -0.06728637218475342,
   0.02684232033789158,
   -0.040794823318719864,
   0.017295753583312035,
   -0.018061229959130287,
   -0.030021455138921738,
   -0.019281182438135147,
   -0.02884584851562977,
   -0.01780518889427185,
   0.0013925704406574368,
   0.024884071201086044,
   -0.055800169706344604,
   -0.062318842858076096,
   0.02584764175117016,
   0.01533286739140749,
   -0.046591866761446,
   0.013576552271842957,
   0.11364924162626266,
   0.00576383713632822,
   -0.014953678473830223,
   0.0061080073937773705,
   0.03629374876618385,
   0.005544818006455898,
   0.0836009606719017,
   0.08921158313751221,
   0.009148911572992802,
   0.08508393168449402,
   0.04495849087834358,
   0.03634541109204292,
   0.03495343402028084,
   -0.008176715113222599,
   0.04589567705988884,
   0.17109236121177673,
   0.04085356369614601,
   0.024069976061582565,
   -0.040606580674648285,
   0.03141756355762482,
   0.003983448725193739,
   0.03276918828487396,
   -0.04044102504849434,
   0.039461150765419006,
   0.04055006057024002,
   -0.02630348689854145,
   -0.07194703072309494,
   -0.048160258680582047,
   -0.06355971097946167,
   -0.034395527094602585,
   0.010917656123638153,
   0.007130216807126999,
   0.0059699397534132,
   -0.026198433712124825,
   -0.05512506887316704,
   -0.04510047659277916,
   -0.022665243595838547,
   0.037295520305633545,
   -0.0271278228610754,
   0.049319252371788025,
   0.0059521677903831005,
   -0.009002920240163803,
   0.016252409666776657,
   0.047067079693078995,
   0.04762159660458565,
   -0.018225345760583878,
   0.004621571861207485,
   -0.0789421945810318,
   0.006487048231065273,
   0.04680205136537552,
   -0.034601885825395584,
   1.1631167626501135e-32,
   -0.019548239186406136,
   0.07630410045385361,
   0.04814128205180168,
   0.020194096490740776,
   0.08964180946350098,
   0.0514264740049839,
   -0.04263899475336075,
   -0.027049794793128967,
   -0.10513424873352051,
   -0.056634411215782166,
   -0.1339838206768036,
   -0.09844935685396194,
   0.0553702637553215,
   0.0303665678948164,
   -0.057359784841537476,
   -0.04482853412628174,
   0.007602156605571508,
   0.05849496275186539,
   -0.02500443533062935,
   -0.0831679031252861,
   0.0620962530374527,
   0.04151422902941704,
   -0.02811223641037941,
   -0.032999832183122635,
   -0.039081886410713196,
   0.03795275464653969,
   0.001799903460778296,
   0.09782125055789948,
   -0.015848448500037193,
   0.004430828616023064,
   -0.02467116340994835,
   0.01627720147371292,
   -0.07830329239368439,
   -0.08740530908107758,
   0.0013250014744699001,
   -0.05934200808405876,
   -0.07312677055597305,
   -0.028593609109520912,
   0.05484054610133171,
   0.017013663426041603,
   -0.036652572453022,
   -0.020379377529025078,
   -0.05990813672542572,
   0.05172919109463692,
   0.02035595290362835,
   -0.03389650955796242,
   -0.003111664205789566,
   0.0690518245100975,
   -0.03227884694933891,
   0.013788189738988876,
   0.02476329728960991,
   -0.07302097976207733,
   0.004393118899315596,
   0.06894262135028839,
   -0.02210146002471447,
   0.026108527556061745,
   -0.0995739996433258,
   0.04361740127205849,
   0.06726258993148804,
   -0.026258528232574463,
   -0.08698582649230957,
   -0.028778154402971268,
   -0.03855820372700691,
   0.01689876988530159,
   -0.008590102195739746,
   -0.08192413300275803,
   0.004668745212256908,
   -0.04599344730377197,
   0.01686832122504711,
   0.04104551672935486,
   0.06147473305463791,
   -0.02566719986498356,
   0.06916435807943344,
   0.06073461472988129,
   0.09907449036836624,
   0.022538213059306145,
   0.06964915245771408,
   0.02408255822956562,
   0.013375760987401009,
   0.07022766023874283,
   -0.03462446480989456,
   0.005080505274236202,
   -0.06774523109197617,
   -0.0003278667281847447,
   -0.08148021250963211,
   -0.10703947395086288,
   -0.03164586424827576,
   -0.011165131814777851,
   0.01786208339035511,
   -0.00710050156340003,
   0.02633124589920044,
   -0.08655443042516708,
   -0.05937293544411659,
   -0.0007504976820200682,
   -0.009011083282530308,
   -1.2094040567656488e-32,
   0.09958890080451965,
   0.04268789663910866,
   0.03468776494264603,
   -0.07310187071561813,
   0.051267433911561966,
   -0.015804564580321312,
   -0.030436517670750618,
   -0.09577895700931549,
   0.06486444920301437,
   -0.014715990982949734,
   0.1285076141357422,
   0.012807497754693031,
   0.04072052612900734,
   0.007929117418825626,
   -0.013541744090616703,
   0.0698506310582161,
   0.07938341796398163,
   -0.014638402499258518,
   -0.02948484942317009,
   0.0178113654255867,
   -0.012324081733822823,
   0.11676028370857239,
   -0.12352794408798218,
   0.01935862936079502,
   -0.01658787950873375,
   0.013984955847263336,
   0.059635527431964874,
   -0.01932441256940365,
   0.03391094133257866,
   0.0916295051574707,
   0.0027666790410876274,
   0.015913188457489014,
   -0.0532645583152771,
   0.00767865777015686,
   0.05161130428314209,
   0.008888592012226582,
   0.07349412888288498,
   -0.08208175748586655,
   -0.018297873437404633,
   0.01630297116935253,
   0.006101557053625584,
   0.042103253304958344,
   -0.0364467017352581,
   -0.05424446985125542,
   0.051235634833574295,
   -0.009894569404423237,
   -0.009885326027870178,
   0.05941745266318321,
   -0.009575922042131424,
   -0.03654801845550537,
   -0.0050314306281507015,
   -0.04146185889840126,
   0.02507575787603855,
   0.00393027113750577,
   0.11595418304204941,
   0.032028064131736755,
   0.015193917788565159,
   -0.08922804892063141,
   0.04010188207030296,
   -0.012138963676989079,
   0.0033400743268430233,
   0.006384639535099268,
   0.0489225834608078,
   0.059150487184524536,
   0.029915504157543182,
   0.04230307415127754,
   -0.019809197634458542,
   0.023347605019807816,
   0.043769240379333496,
   -0.050795089453458786,
   -0.013771635480225086,
   0.01744106411933899,
   -0.008307875134050846,
   0.06968345493078232,
   -0.011915896087884903,
   0.047568779438734055,
   -0.057258427143096924,
   -0.004690965171903372,
   -0.035875409841537476,
   0.014761083759367466,
   0.02923683635890484,
   -0.04007578641176224,
   0.025890300050377846,
   -0.07591235637664795,
   -0.047286488115787506,
   -0.040010642260313034,
   0.009800011292099953,
   0.041199956089258194,
   -0.004457308445125818,
   -0.06256028264760971,
   0.03500619903206825,
   -0.03164411708712578,
   -0.008729718625545502,
   0.1448160856962204,
   0.05098456144332886,
   -5.667649816132325e-08,
   0.04552558436989784,
   -0.14494885504245758,
   -0.01714271865785122,
   -0.11624489724636078,
   -0.05519966036081314,
   0.019103841856122017,
   -0.018483661115169525,
   -0.010680902749300003,
   0.10378718376159668,
   0.029039600864052773,
   -0.0006207487313076854,
   0.051209114491939545,
   -0.00207632128149271,
   0.061567965894937515,
   -0.026897646486759186,
   0.021153651177883148,
   0.016178082674741745,
   -0.02501019462943077,
   -0.048041604459285736,
   -0.019774576649069786,
   -0.00681261857971549,
   -0.00655484339222312,
   -0.036808691918849945,
   -0.04307912290096283,
   0.0727047547698021,
   -0.033699240535497665,
   -0.020984407514333725,
   -0.00042101586586795747,
   0.019858133047819138,
   -0.04467127099633217,
   -0.022004634141921997,
   -0.004555344115942717,
   0.10267955809831619,
   0.005125486757606268,
   0.010916639119386673,
   0.009279392659664154,
   0.018223803490400314,
   -0.06698024272918701,
   0.008098178543150425,
   0.11122651398181915,
   0.05366033688187599,
   -0.08099259436130524,
   -0.054397668689489365,
   -0.040087372064590454,
   -0.011957738548517227,
   -0.09655839204788208,
   0.026221277192234993,
   -0.013105328194797039,
   -0.07770681381225586,
   -0.08727739751338959,
   -0.020705267786979675,
   0.03227957710623741,
   0.0013156547211110592,
   -0.033838801085948944,
   -0.023670010268688202,
   0.07184009253978729,
   -0.06651438027620316,
   0.05404360219836235,
   0.03070203959941864,
   -0.09840656816959381,
   0.0018445114837959409,
   -0.05030288174748421,
   0.029676176607608795,
   -0.023130908608436584],
  [0.04754897207021713,
   -0.09599931538105011,
   -0.12249145656824112,
   -0.03506482020020485,
   0.03120911866426468,
   -0.058353062719106674,
   0.03759680315852165,
   0.12144768983125687,
   0.03653908893465996,
   0.002077482407912612,
   -0.05691555142402649,
   0.1020406112074852,
   0.03591756150126457,
   0.09282480180263519,
   -0.04883643984794617,
   0.049470290541648865,
   0.02363290823996067,
   0.05159487947821617,
   -0.029133696109056473,
   0.028843004256486893,
   0.04180411621928215,
   -0.049803514033555984,
   0.08560922741889954,
   0.038932912051677704,
   -0.004261158872395754,
   0.03136803209781647,
   0.015728341415524483,
   0.026381636038422585,
   -0.08761588484048843,
   -0.023588305339217186,
   0.030127665027976036,
   0.024885188788175583,
   0.06436506658792496,
   -0.11429942399263382,
   -0.011076908558607101,
   0.008002480491995811,
   -0.04761311784386635,
   -0.05445028468966484,
   0.07678429037332535,
   0.058800917118787766,
   0.035475149750709534,
   0.029401864856481552,
   0.002136436989530921,
   0.04510597884654999,
   -0.03010631538927555,
   -0.07361655682325363,
   -0.01254186499863863,
   0.007711658254265785,
   0.007012758869677782,
   0.04614781588315964,
   -0.022273816168308258,
   0.0033507707994431257,
   -0.08582726866006851,
   0.022026779130101204,
   -0.020616047084331512,
   -0.04837225377559662,
   -0.060514312237501144,
   0.018661439418792725,
   -0.04165787249803543,
   -0.02546721324324608,
   -0.05072234943509102,
   0.028349237516522408,
   -0.0067651160061359406,
   -0.021297426894307137,
   -0.042600229382514954,
   0.022207967936992645,
   -0.015927987173199654,
   -0.0661701187491417,
   0.05289275571703911,
   0.027193808928132057,
   -0.08615998178720474,
   -0.009290697053074837,
   0.07807563245296478,
   0.047383662313222885,
   -0.028689615428447723,
   0.013470714911818504,
   0.14666812121868134,
   -0.030292369425296783,
   -0.09789205342531204,
   -0.03805076703429222,
   0.03427945449948311,
   -0.03056107833981514,
   -0.013117102906107903,
   0.04098721593618393,
   0.05052072927355766,
   0.02532719448208809,
   0.017721815034747124,
   0.049221061170101166,
   0.06046115979552269,
   -0.011978153139352798,
   0.06355240941047668,
   0.1192157194018364,
   -0.06401997804641724,
   -0.01774844154715538,
   -0.00219049584120512,
   0.011837578378617764,
   -0.03237229958176613,
   0.011629258282482624,
   0.01865018904209137,
   -0.011450367979705334,
   0.04600301384925842,
   -0.06102687492966652,
   -0.010289940983057022,
   0.044211748987436295,
   0.03459462150931358,
   -0.010272328741848469,
   -0.029550453647971153,
   0.05249602720141411,
   -0.07888416200876236,
   0.046373941004276276,
   0.004709053318947554,
   0.011831622570753098,
   0.029506182298064232,
   0.04462137818336487,
   -0.012500576674938202,
   0.016723722219467163,
   0.04171103239059448,
   -0.061377473175525665,
   -0.0678846463561058,
   0.01159389317035675,
   0.040679436177015305,
   0.05079971253871918,
   0.10708418488502502,
   -0.09292297810316086,
   0.05471237748861313,
   0.0480477549135685,
   0.035550083965063095,
   4.8208257596290374e-33,
   -0.015341594815254211,
   0.022604618221521378,
   0.02159273810684681,
   0.05291718617081642,
   0.05212090536952019,
   0.14011360704898834,
   -0.028377383947372437,
   -0.0009408874902874231,
   0.01907791756093502,
   -0.054290737956762314,
   -0.052072349935770035,
   -0.01890314742922783,
   0.038489799946546555,
   -0.021395228803157806,
   -0.022542214021086693,
   0.07216061651706696,
   0.06104939430952072,
   0.030358286574482918,
   0.05943337455391884,
   0.05423574522137642,
   0.011575485579669476,
   -0.04850291833281517,
   -0.035140324383974075,
   0.041355375200510025,
   -0.003909564111381769,
   0.016126582399010658,
   -0.014214370399713516,
   0.05328750237822533,
   -0.004567726515233517,
   -0.025327635928988457,
   -0.030662985518574715,
   -0.047847647219896317,
   -0.0239198487251997,
   -0.04038700461387634,
   0.020052233710885048,
   -0.006951584946364164,
   -0.12550963461399078,
   -0.00746981892734766,
   0.05635659396648407,
   0.037748783826828,
   -0.005650071892887354,
   -0.0401458777487278,
   0.03502785041928291,
   0.03190479055047035,
   -0.007140517700463533,
   0.046578921377658844,
   -0.09677569568157196,
   0.0973796397447586,
   0.03228207305073738,
   -0.04275044426321983,
   0.030430354177951813,
   -0.07830113172531128,
   0.036858197301626205,
   0.013516340404748917,
   -0.03301665186882019,
   0.039747025817632675,
   -0.06225854903459549,
   -0.002769975457340479,
   0.06764226406812668,
   -0.039492085576057434,
   -0.044161275029182434,
   -0.015444722026586533,
   -0.014758514240384102,
   0.07797279208898544,
   0.03499316796660423,
   -0.07369222491979599,
   -0.06385480612516403,
   0.005820122547447681,
   0.0009148523095063865,
   -0.0014461346436291933,
   0.05260365456342697,
   -0.09510993957519531,
   0.013614585623145103,
   0.032214947044849396,
   0.025627728551626205,
   0.03863541781902313,
   0.06983011960983276,
   0.034000806510448456,
   0.042467232793569565,
   0.03277308866381645,
   0.026128029450774193,
   0.02257632091641426,
   -0.02367941476404667,
   -0.010921219363808632,
   -0.06426136940717697,
   -0.028443412855267525,
   -0.049905095249414444,
   0.03983194753527641,
   0.06330952793359756,
   0.001284802216105163,
   0.005681908223778009,
   -0.09784693270921707,
   -0.08247257769107819,
   -0.04586615785956383,
   -0.027006227523088455,
   -4.2052362658346985e-33,
   0.07591462135314941,
   0.06667027622461319,
   0.013572216965258121,
   -0.0329526886343956,
   -0.0014490581816062331,
   0.007555150426924229,
   0.015372338704764843,
   -0.01814132183790207,
   0.04981497675180435,
   -0.05605309084057808,
   0.09484498202800751,
   0.020784132182598114,
   -0.1048479750752449,
   -0.06686093658208847,
   -0.007957644760608673,
   0.00184071552939713,
   -0.007741341833025217,
   0.09998281300067902,
   0.01787465438246727,
   0.013896933756768703,
   -0.07081195712089539,
   0.07593423873186111,
   -0.04230687394738197,
   0.07922469079494476,
   0.055383797734975815,
   -0.051691994071006775,
   0.01842000149190426,
   -0.054792262613773346,
   0.055097971111536026,
   0.0587284155189991,
   0.0981043353676796,
   -0.004112342372536659,
   -0.011754763312637806,
   0.019278766587376595,
   0.05704247206449509,
   0.051865462213754654,
   0.011841927655041218,
   -0.05514282360672951,
   -0.016873735934495926,
   0.06228704750537872,
   0.01636938564479351,
   0.005548679269850254,
   -0.04670711234211922,
   -0.050734568387269974,
   0.0029721956234425306,
   0.021706508472561836,
   -0.03788985311985016,
   -0.02470095269382,
   0.009648068808019161,
   -0.07722797244787216,
   0.009504587389528751,
   -0.10378143191337585,
   -0.022319231182336807,
   -0.05419734865427017,
   0.03196612000465393,
   0.020694022998213768,
   0.06263825297355652,
   -0.017445949837565422,
   0.09675604850053787,
   -0.0717785581946373,
   0.02176824025809765,
   -0.0037372312508523464,
   0.013767766766250134,
   -0.037754811346530914,
   -0.08451786637306213,
   0.023272963240742683,
   0.01247422955930233,
   0.08438902348279953,
   0.03773995861411095,
   0.015696905553340912,
   -0.0014700808096677065,
   0.04137663543224335,
   0.01948942244052887,
   0.03569202125072479,
   -0.02163391187787056,
   0.08608226478099823,
   -0.10272490233182907,
   -0.01761697232723236,
   -0.023262515664100647,
   0.0068892245180904865,
   0.019358377903699875,
   -0.038749706000089645,
   -0.01810838282108307,
   0.003360619070008397,
   -0.09227333217859268,
   -0.08846118301153183,
   -0.0024244787637144327,
   0.05970274284482002,
   -0.04324223846197128,
   -0.038793034851551056,
   0.008663279935717583,
   -0.09933847934007645,
   -0.031031712889671326,
   0.09803178906440735,
   0.07035988569259644,
   -5.033028216416824e-08,
   0.02616390958428383,
   -0.028603767976164818,
   -0.01575288362801075,
   0.0032925670966506004,
   -0.10347512364387512,
   -0.021368063986301422,
   0.009896285831928253,
   -0.011925403960049152,
   0.10655615478754044,
   0.039198294281959534,
   -0.12536610662937164,
   0.05760817974805832,
   -0.008687611669301987,
   0.056026168167591095,
   -0.09648285061120987,
   0.029314449056982994,
   -0.049683742225170135,
   -0.053971052169799805,
   -0.019483722746372223,
   0.03456566110253334,
   -0.05515388399362564,
   0.03005577065050602,
   -0.08844467252492905,
   0.0013486731331795454,
   0.09236694872379303,
   -0.061275236308574677,
   0.01694602146744728,
   0.010253600776195526,
   0.017964381724596024,
   -0.009386492893099785,
   0.08920087665319443,
   -0.033671241253614426,
   0.05729757249355316,
   0.00883860606700182,
   -0.034399088472127914,
   -0.058227553963661194,
   2.4008761556615354e-06,
   0.00026894506299868226,
   0.03231215476989746,
   0.0966804102063179,
   -0.0006483122706413269,
   -0.13197526335716248,
   -0.02092840149998665,
   0.005620595999062061,
   -0.0580979660153389,
   -0.044831257313489914,
   -0.07905002683401108,
   0.023498041555285454,
   -0.07024542987346649,
   -0.05900215357542038,
   0.05686967447400093,
   0.034116845577955246,
   -0.05662116780877113,
   -0.05700559541583061,
   -0.03738594055175781,
   0.004343108739703894,
   -0.010400013998150826,
   -0.0012106066569685936,
   -0.011448941193521023,
   -0.10172943025827408,
   -0.05888138711452484,
   -0.022057009860873222,
   0.09900611639022827,
   -0.047255273908376694],
  [0.04430558159947395,
   -0.04939784109592438,
   -0.10671574622392654,
   -0.07076289504766464,
   0.02284681797027588,
   -0.003881315467879176,
   0.003441686276346445,
   -0.0067611937411129475,
   0.03427709639072418,
   0.028871923685073853,
   -0.06177197024226189,
   0.07321511954069138,
   -0.018481049686670303,
   0.0754205584526062,
   -0.02378339320421219,
   0.08134376257658005,
   -0.024160318076610565,
   0.008200409822165966,
   0.002350153401494026,
   0.09102530777454376,
   0.005506679881364107,
   -0.03940657526254654,
   0.0884193480014801,
   0.11464128643274307,
   -0.054324690252542496,

In [14]:
# Extract Text from corpus ids
corpus_id = "234488766"

# query example of finding articles by corpus id
seperated_text = lang_collect.get(
    where={"corpusid": "237156001"}, include=["documents", "embeddings", "metadatas"]
)

seperated_text

{'ids': ['237156001_0',
  '237156001_1',
  '237156001_2',
  '237156001_3',
  '237156001_4',
  '237156001_5',
  '237156001_6',
  '237156001_7',
  '237156001_8',
  '237156001_9',
  '237156001_10',
  '237156001_11',
  '237156001_12',
  '237156001_13',
  '237156001_14',
  '237156001_15',
  '237156001_16',
  '237156001_17',
  '237156001_18',
  '237156001_19',
  '237156001_20',
  '237156001_21',
  '237156001_22',
  '237156001_23',
  '237156001_24',
  '237156001_25',
  '237156001_26',
  '237156001_27',
  '237156001_28',
  '237156001_29',
  '237156001_30',
  '237156001_31',
  '237156001_32',
  '237156001_33',
  '237156001_34',
  '237156001_35',
  '237156001_36',
  '237156001_37',
  '237156001_38',
  '237156001_39',
  '237156001_40',
  '237156001_41',
  '237156001_42',
  '237156001_43',
  '237156001_44',
  '237156001_45',
  '237156001_46',
  '237156001_47',
  '237156001_48'],
 'embeddings': [[0.018608108162879944,
   -0.0204623956233263,
   0.006335105746984482,
   -0.042212631553411484,
   0.0011242660693824291,
   -0.02441497892141342,
   -0.04221412166953087,
   0.08908890932798386,
   -0.07145144790410995,
   -0.044665832072496414,
   0.0021608765237033367,
   -0.016351992264389992,
   0.13648320734500885,
   0.06027885153889656,
   -0.03512869402766228,
   0.014524433761835098,
   0.007249546702951193,
   -0.029911277815699577,
   -0.022368349134922028,
   -0.0238503310829401,
   -0.07291949540376663,
   0.07563644647598267,
   -0.01925303041934967,
   -0.082515187561512,
   -0.03296766057610512,
   -0.04604293406009674,
   -0.022492777556180954,
   -0.07184974104166031,
   0.017537549138069153,
   -0.031478382647037506,
   -0.04107782244682312,
   0.0605606846511364,
   -0.05939121171832085,
   -0.07607736438512802,
   0.02765822224318981,
   0.01685277186334133,
   -0.06545481830835342,
   0.0022635662462562323,
   -0.031361017376184464,
   0.013458475470542908,
   0.08353672921657562,
   -0.03526388853788376,
   0.04129442945122719,
   -0.05860121175646782,
   -0.0077069527469575405,
   0.0052750129252672195,
   -0.03546782582998276,
   0.027822377160191536,
   0.048434872180223465,
   0.0895516648888588,
   -0.02331126481294632,
   -0.06379204243421555,
   -0.06188191846013069,
   0.10443544387817383,
   -0.08773179352283478,
   -0.027144864201545715,
   -0.06373175978660583,
   -0.0839451402425766,
   -0.0012709638103842735,
   -0.07289379835128784,
   -0.10250581055879593,
   0.060023996978998184,
   0.054856546223163605,
   -0.01809879019856453,
   0.01629909873008728,
   0.055888984352350235,
   -0.04941216856241226,
   -0.0588226281106472,
   0.0552842803299427,
   0.02766343019902706,
   0.03942733630537987,
   0.018147775903344154,
   -0.09643048048019409,
   0.1470438688993454,
   -0.09889299422502518,
   0.012587775476276875,
   0.05219525843858719,
   -0.04790866747498512,
   -0.036048490554094315,
   0.03425385802984238,
   -0.04053227975964546,
   -0.01847439631819725,
   0.08995689451694489,
   -0.04686456546187401,
   -0.024052735418081284,
   0.048747409135103226,
   -0.03875439986586571,
   0.024771995842456818,
   -0.13112901151180267,
   -0.018702208995819092,
   0.13739269971847534,
   0.05508039891719818,
   -0.012883417308330536,
   0.0720382109284401,
   -0.024334054440259933,
   -0.03154801204800606,
   0.027908315882086754,
   0.11089826375246048,
   -0.030010269954800606,
   -0.05235106125473976,
   -0.073123499751091,
   -0.04178408160805702,
   0.02922869846224785,
   -0.02990048937499523,
   -0.02359144575893879,
   -0.08760051429271698,
   0.02632479928433895,
   -0.08282854408025742,
   -0.0018202137434855103,
   -0.050094153732061386,
   0.01186252199113369,
   0.06715498864650726,
   0.06812754273414612,
   -0.10394390672445297,
   0.027455197647213936,
   0.06516663730144501,
   0.005664631258696318,
   0.04781382903456688,
   -0.05808020383119583,
   -0.03622268885374069,
   0.0003317189693916589,
   -0.05113620311021805,
   0.004643983673304319,
   -0.08659107983112335,
   0.04296670854091644,
   -0.01863488182425499,
   -0.03430549055337906,
   1.6833079103775157e-32,
   -0.04924536496400833,
   0.004201152827590704,
   0.14064842462539673,
   0.0179643165320158,
   0.02504461631178856,
   0.03233085200190544,
   0.032346103340387344,
   -0.04284093901515007,
   0.02053048461675644,
   -0.03894760087132454,
   -0.07145723700523376,
   0.03180710971355438,
   0.025437800213694572,
   -0.045578133314847946,
   -0.10985235124826431,
   0.021122444421052933,
   0.0061973887495696545,
   -0.01141373161226511,
   -0.033626895397901535,
   0.012454736977815628,
   0.04030148684978485,
   -0.028085675090551376,
   0.028658583760261536,
   -0.008546469733119011,
   -0.08388421684503555,
   0.02398216351866722,
   0.015229985117912292,
   0.020594675093889236,
   -0.002215298358350992,
   0.021051811054348946,
   0.0035928795114159584,
   0.02713354118168354,
   -0.024247074499726295,
   -0.051876455545425415,
   -0.056876979768276215,
   -0.023347647860646248,
   -0.043328456580638885,
   -6.567445961991325e-05,
   -0.01853392831981182,
   -0.026123374700546265,
   -0.004006465431302786,
   -0.004220650997012854,
   -0.07529446482658386,
   0.019721511751413345,
   0.007345773279666901,
   -0.09240645170211792,
   -0.04758136346936226,
   0.015461086295545101,
   -0.004784749820828438,
   -0.10615650564432144,
   0.03253428637981415,
   -0.02490927465260029,
   -0.01819794625043869,
   -0.015507878735661507,
   0.020630517974495888,
   -0.004756220616400242,
   -0.008997189812362194,
   -0.0203808955848217,
   -0.0054616183042526245,
   0.06783713400363922,
   0.1130642369389534,
   0.04383983835577965,
   0.016346832737326622,
   0.061307381838560104,
   -0.07970266789197922,
   0.016252484172582626,
   -0.03811614587903023,
   -0.13185514509677887,
   0.01098188292235136,
   -0.06148621812462807,
   0.02826639823615551,
   -0.06752371042966843,
   -0.020406801253557205,
   -0.023300588130950928,
   0.061397068202495575,
   -0.05351320281624794,
   0.014069882221519947,
   -0.022012995555996895,
   0.03956525772809982,
   -0.014567353762686253,
   -0.01888503134250641,
   -0.026944274082779884,
   0.07291311770677567,
   0.01313055120408535,
   -0.034254640340805054,
   -0.05941058322787285,
   0.009894413873553276,
   0.06646900624036789,
   -0.048431940376758575,
   -0.03680429607629776,
   0.021065127104520798,
   0.034356627613306046,
   -0.07198385894298553,
   0.0718083381652832,
   -0.016633084043860435,
   -1.8700658977955513e-32,
   0.0748688280582428,
   -0.009986490942537785,
   -0.001794809359125793,
   0.013927151449024677,
   0.07978565990924835,
   0.0204140767455101,
   0.12556663155555725,
   -0.01638106070458889,
   0.055978983640670776,
   -0.08507407456636429,
   0.05951538681983948,
   -0.012373926118016243,
   -0.06967541575431824,
   -0.020111652091145515,
   -0.0038779445458203554,
   0.07067940384149551,
   0.04524974897503853,
   -0.04843863099813461,
   -0.0804465115070343,
   -0.007458996959030628,
   -0.013856617733836174,
   -0.07829977571964264,
   -0.019626814872026443,
   0.00436617573723197,
   -0.04593384265899658,
   0.015856057405471802,
   -0.04124968498945236,
   -0.049042709171772,
   -0.011939547024667263,
   0.03899933025240898,
   -0.00309847597964108,
   0.09497445076704025,
   0.004361980594694614,
   0.07360410690307617,
   -0.06010248512029648,
   -0.05517897382378578,
   0.07133955508470535,
   -0.0646682158112526,
   0.07249493151903152,
   -0.06263231486082077,
   0.043458785861730576,
   0.03752995654940605,
   -0.008835573680698872,
   0.04429185017943382,
   0.06818971782922745,
   0.01831022836267948,
   0.018592335283756256,
   -0.08440106362104416,
   0.04749260097742081,
   0.046257004141807556,
   -0.005636540241539478,
   0.026977544650435448,
   -0.0010504343081265688,
   0.033723603934049606,
   0.002358838450163603,
   0.05068572238087654,
   -0.06693975627422333,
   -0.03967529535293579,
   -0.048190291970968246,
   -0.04231194406747818,
   -0.0060180434957146645,
   0.0319984070956707,
   -0.06252421438694,
   -0.01961922086775303,
   -0.01774566061794758,
   0.10609319806098938,
   0.07160715013742447,
   0.02115393429994583,
   0.07214102894067764,
   -0.08129546791315079,
   -0.025453010573983192,
   -0.007492030970752239,
   -0.09309497475624084,
   0.009573129005730152,
   0.039912838488817215,
   0.0402180515229702,
   -0.05090167745947838,
   0.03290485218167305,
   -0.023202024400234222,
   -0.005601131822913885,
   -0.06461194902658463,
   0.019954973831772804,
   -0.030839214101433754,
   0.009840833023190498,
   0.021119875833392143,
   -0.033876411616802216,
   0.00975035224109888,
   -0.03653097525238991,
   -0.016065014526247978,
   0.023243693634867668,
   -0.047969818115234375,
   -0.043626196682453156,
   -0.09337899088859558,
   0.031121090054512024,
   0.11676742136478424,
   -7.007167823758209e-08,
   -0.07388380914926529,
   -0.04217377305030823,
   0.019722314551472664,
   -0.016933919861912727,
   -0.02379276603460312,
   0.0005162581219337881,
   -0.011472541838884354,
   0.04581158980727196,
   0.06278272718191147,
   0.028516296297311783,
   0.02896863967180252,
   0.029588405042886734,
   0.00028027634834870696,
   -0.049575284123420715,
   0.07120896875858307,
   0.04099196568131447,
   -0.002649592701345682,
   -0.01912451535463333,
   -0.012202712707221508,
   -0.048954110592603683,
   0.05306100472807884,
   -0.0248451828956604,
   0.06984420865774155,
   0.028848029673099518,
   -0.03394254297018051,
   0.029444100335240364,
   -0.034558989107608795,
   0.03561943396925926,
   -0.03366467356681824,
   -0.023249415680766106,
   -0.04392491281032562,
   -0.042302701622247696,
   -0.0386231392621994,
   -0.0571582093834877,
   0.06527414172887802,
   0.07220172137022018,
   0.020755093544721603,
   0.0018244385719299316,
   0.09817954152822495,
   0.08311624079942703,
   -0.057242561131715775,
   -0.06101469695568085,
   0.0024922967422753572,
   0.00024121449678204954,
   0.010701843537390232,
   -0.0784255787730217,
   -0.05326969549059868,
   0.055271826684474945,
   -0.008145490661263466,
   -0.08375151455402374,
   0.08479917794466019,
   -0.07934986799955368,
   0.016247360035777092,
   -0.034416887909173965,
   -0.013600132428109646,
   0.15342716872692108,
   -0.045471131801605225,
   -0.005998591426759958,
   0.0019293256336823106,
   0.04541865363717079,
   0.0011767045361921191,
   -0.04296533763408661,
   0.0175916850566864,
   0.007802433334290981],
  [-0.00014770553389098495,
   -0.008831212297081947,
   0.0035706355702131987,
   -0.06236816570162773,
   0.03692592307925224,
   -0.02297896519303322,
   -0.06490098685026169,
   0.08858965337276459,
   -0.03636106848716736,
   -0.07506952434778214,
   -0.01799333281815052,
   -0.032231565564870834,
   0.1498454362154007,
   0.05664077028632164,
   -0.015242454595863819,
   0.024358153343200684,
   -0.001296267961151898,
   -0.025019843131303787,
   -0.009256841614842415,
   -0.03047196939587593,
   -0.04614458233118057,
   0.0713270902633667,
   -0.028489550575613976,
   -0.07895294576883316,
   -0.019611842930316925,
   -0.04070531949400902,
   0.019701875746250153,
   -0.055594176054000854,
   0.023534351959824562,
   0.017515787854790688,
   -0.002748260274529457,
   0.05564199760556221,
   -0.04659125953912735,
   -0.051250386983156204,
   -0.006792599335312843,
   0.04939521849155426,
   -0.06719284504652023,
   -0.006694926880300045,
   -0.020433925092220306,
   0.040395233780145645,
   0.0725458562374115,
   0.012649781070649624,
   0.02622867003083229,
   -0.07101824879646301,
   0.012877719476819038,
   0.02729754149913788,
   -0.04509536921977997,
   0.011078366078436375,
   0.033105235546827316,
   0.10545371472835541,
   -0.0070289988070726395,
   -0.05235184356570244,
   -0.07853026688098907,
   0.09582377225160599,
   -0.10511437803506851,
   -0.023694608360528946,
   -0.0659126564860344,
   -0.05232364311814308,
   -0.004972658585757017,
   -0.03549002856016159,
   -0.08831413090229034,
   0.044245779514312744,
   0.07692423462867737,
   -0.03490900993347168,
   -0.001011654152534902,
   0.0411694198846817,
   -0.06845659017562866,
   -0.050449468195438385,
   0.05391700193285942,
   0.005907600279897451,
   0.0007177470251917839,
   0.00951141957193613,
   -0.06952227652072906,
   0.132330983877182,
   -0.07962147146463394,
   0.020051265135407448,
   0.05620815232396126,
   -0.06659721583127975,
   -0.024311551824212074,
   0.03925967216491699,
   -0.018277302384376526,
   0.01783846504986286,
   0.057266104966402054,
   0.006174908950924873,
   0.021065836772322655,
   0.06318286806344986,
   -0.02368966117501259,
   0.01743701845407486,
   -0.10018203407526016,
   0.010216949507594109,
   0.1476415991783142,
   0.0651259645819664,
   0.00019528889970388263,
   0.06828885525465012,
   -0.03190317377448082,
   -0.043376993387937546,
   0.0063572293147444725,
   0.10213321447372437,
   -0.04209734499454498,
   -0.053328029811382294,
   -0.07536885887384415,
   -0.0320773646235466,
   -0.0017034743214026093,
   -0.10339140892028809,
   0.027235964313149452,
   -0.07100848853588104,
   0.0421290285885334,
   -0.07448966056108475,
   0.01615392416715622,
   -0.02110903523862362,
   0.003088578348979354,
   0.05801200866699219,
   0.06471019238233566,
   -0.10716819018125534,
   -0.003143157111480832,
   0.06157733500003815,
   0.012855509296059608,
   0.03761734068393707,
   -0.0809607282280922,
   -0.045071762055158615,
   0.008544523268938065,
   -0.08423292636871338,
   0.017863072454929352,
   -0.1017322689294815,
   0.02672579325735569,
   -0.010202078148722649,
   -0.03963867202401161,
   1.4365094918761178e-32,
   -0.03555039316415787,
   0.004408716689795256,
   0.1286565661430359,
   0.03186031058430672,
   0.0006166528910398483,
   0.02945253625512123,
   0.046109892427921295,
   -0.021385949105024338,
   0.02216486446559429,
   -0.005814803764224052,
   -0.07591840624809265,
   0.06625298410654068,
   0.003973532002419233,
   -0.05010911449790001,
   -0.08234422653913498,
   0.018901020288467407,
   0.0008341186330653727,
   -0.04438028112053871,
   0.025196703150868416,
   0.001534425187855959,
   0.0347297377884388,
   -0.03239469230175018,
   0.02400161512196064,
   -0.04014698415994644,
   -0.09075503796339035,
   0.01073344424366951,
   0.050555504858493805,
   0.032530415803194046,
   -0.01118098758161068,
   -0.0059097581543028355,
   -0.02396293170750141,
   0.012361885979771614,
   -0.034640032798051834,
   -0.058410901576280594,
   -0.04182096943259239,
   -0.044310394674539566,
   -0.01542078796774149,
   0.02679344452917576,
   -0.04135182872414589,
   -0.012218206189572811,
   -0.0019558954518288374,
   -0.01845361478626728,
   -0.073790542781353,
   0.022771932184696198,
   -0.015508107841014862,
   -0.0714067742228508,
   -0.07843232899904251,
   0.021429847925901413,
   0.019517267122864723,
   -0.08727169781923294,
   0.041170503944158554,
   -0.06471145153045654,
   0.041074272245168686,
   0.012786277569830418,
   -0.01995459571480751,
   -0.016786234453320503,
   -0.003136010142043233,
   -0.02128054015338421,
   0.0053156595677137375,
   0.06357093900442123,
   0.08998622745275497,
   0.02417396381497383,
   0.046937551349401474,
   0.08148588985204697,
   -0.06616992503404617,
   -0.011441042646765709,
   -0.04464247450232506,
   -0.12093593180179596,
   0.028965232893824577,
   -0.07979847490787506,
   0.058010827749967575,
   -0.07013842463493347,
   -0.016029899939894676,
   -0.03379284590482712,
   0.03297792002558708,
   -0.06523478031158447,
   0.01636805199086666,
   0.005260172300040722,
   0.03366962820291519,
   0.0033876525703817606,
   -0.012050574645400047,
   -0.042814046144485474,
   0.054489631205797195,
   0.034055449068546295,
   -0.0410100519657135,
   -0.07278580218553543,
   0.009469261392951012,
   0.057654790580272675,
   -0.026115870103240013,
   -0.05241534113883972,
   -0.013184803538024426,
   0.005291214678436518,
   -0.05438917502760887,
   0.08918412774801254,
   -0.02919829450547695,
   -1.5223850847386462e-32,
   0.06382512301206589,
   -0.02923685498535633,
   -0.007453566882759333,
   0.006225884426385164,
   0.09068824350833893,
   0.051258478313684464,
   0.12735049426555634,
   -0.030995426699519157,
   0.04526442661881447,
   -0.06245141476392746,
   0.07164940983057022,
   -0.016502922400832176,
   -0.04809419438242912,
   0.027559446170926094,
   0.03431200236082077,
   0.07853199541568756,
   0.03901980444788933,
   -0.04245058447122574,
   -0.09253297001123428,
   0.020216258242726326,
   -0.011463045142591,
   -0.0691806897521019,
   -0.014116552658379078,
   0.02874734252691269,
   -0.024921594187617302,
   0.03006909228861332,
   -0.005849994719028473,
   -0.04728173837065697,
   -0.00346734537743032,
   0.03634941577911377,
   0.0458403080701828,
   0.1072445809841156,
   0.007708123419433832,
   0.08348254859447479,
   -0.05944153666496277,
   -0.06901556253433228,
   0.09064827859401703,
   -0.08625323325395584,
   0.06558901071548462,
   -0.05670173093676567,
   0.025046775117516518,
   0.021043410524725914,
   -0.0494525171816349,
   0.06015831232070923,
   0.05679082125425339,
   0.053683314472436905,
   0.06651902198791504,
   -0.11308547109365463,
   0.03846583142876625,
   0.04836282879114151,
   0.007371337618678808,
   -0.007922687567770481,
   -0.0062051513232290745,
   0.0645529106259346,
   -0.02016993798315525,
   0.05899139493703842,
   -0.08458825945854187,
   -0.020123237743973732,
   -0.016475284472107887,
   -0.05254284664988518,
   0.04515194520354271,
   0.0339086651802063,
   -0.08396898955106735,
   -0.02942080795764923,
   -0.05425151437520981,
   0.11971846222877502,
   0.07962095737457275,
   0.012476119212806225,
   0.08505833148956299,
   -0.08947279304265976,
   -0.02497638389468193,
   0.01694457046687603,
   -0.05179852619767189,
   0.01688558980822563,
   -0.007583911530673504,
   0.015317141078412533,
   -0.03176656737923622,
   -0.011091078631579876,
   -0.023295337334275246,
   -0.0013856905279681087,
   -0.05336332693696022,
   0.023499537259340286,
   -0.027971340343356133,
   0.00049598328769207,
   -0.021437805145978928,
   -0.01783693954348564,
   -0.010910305194556713,
   0.00507676275447011,
   -0.01317905355244875,
   0.018382683396339417,
   -0.05468461290001869,
   -0.03176668658852577,
   -0.10369282960891724,
   0.07478080689907074,
   0.10718698799610138,
   -5.963976690281925e-08,
   -0.046820688992738724,
   -0.048864226788282394,
   0.01631152257323265,
   -0.030477356165647507,
   -0.08140851557254791,
   -0.014308377169072628,
   0.005367287900298834,
   0.015335028059780598,
   0.05433148518204689,
   0.02686362899839878,
   0.025732874870300293,
   0.026270437985658646,
   -0.015886681154370308,
   -0.03155304118990898,
   0.04411865770816803,
   0.03275603428483009,
   0.024339616298675537,
   -0.016492171213030815,
   0.012795960530638695,
   -0.026989605277776718,
   0.06033942475914955,
   -0.02173241414129734,
   0.07864685356616974,
   0.004779162351042032,
   -0.025632040575146675,
   -0.018873678520321846,
   -0.05394190922379494,
   0.045242488384246826,
   -0.018200965598225594,
   -0.006012216676026583,
   -0.06451094150543213,
   -0.028060289099812508,
   -0.04945234954357147,
   -0.0456821545958519,
   0.05843474343419075,
   0.0654592290520668,
   0.012986281886696815,
   -0.00909037422388792,
   0.1026788279414177,
   0.09583020955324173,
   -0.06893793493509293,
   -0.0758499726653099,
   -0.008328311145305634,
   0.0009054459515027702,
   -0.006372668314725161,
   -0.07940857112407684,
   -0.030832435935735703,
   0.036970533430576324,
   0.010382059961557388,
   -0.052950967103242874,
   0.07376528531312943,
   -0.05317825451493263,
   0.002868317300453782,
   -0.040610332041978836,
   -0.03258322551846504,
   0.1282881498336792,
   -0.09191378206014633,
   -0.009285722859203815,
   0.0052256197668612,
   0.0019866926595568657,
   -0.018527256324887276,

In [16]:
# Combine Seperated Text to input into models
def combine_full_text_embeddings(text_embedding):
    final_doc = []
    for i in range(len(text_embedding)):
        final_doc.append(text_embedding[i])
    return " ".join(final_doc)

full_text_example1 = combine_full_text_embeddings(
    seperated_text.get('documents'))
full_text_example1

full_doc_example = full_text["text"][8]
full_doc_example

'Citation: Diagnostic Efficacy of Xpert MTB/RIF Assay in Bronchoalveolar Lavage Fluid for Tracheobronchial Tuberculosis: A Retrospective Analysis\nAugust 2021\n\nPiero Valentini \nJesica Mazza-Stalder \nQiao Liu \nSun Y \nZhang Q \nZhang Q \nLiu C \nZhang H Fu \nY Liu \nY \nHou G \nYue Sun \nInstitute of Respiratory Diseases\nThe First Hospital of China Medical University\nShenyangChina\n\n† \nQing Zhang \nDepartment of Endoscopy\nShenyang Chest Hospital\nShenyangChina\n\n† \nQin Zhang \nInstitute of Respiratory Diseases\nThe First Hospital of China Medical University\nShenyangChina\n\nChang Liu \nDepartment of Endoscopy\nShenyang Chest Hospital\nShenyangChina\n\nHong Zhang \nDepartment of Laboratory\nShenyang Chest Hospital\nShenyangChina\n\nYinghui Fu \nInstitute of Respiratory Diseases\nShenyang Chest Hospital\nShenyangChina\n\nYongyu Liu \nInstitute of Respiratory Diseases\nShenyang Chest Hospital\nShenyangChina\n\nGang Hou \nDepartment of Pulmonary and Critical Care Medicine\nCenter of Respiratory Medicine\nFriendship Hospital\nBeijingChina-Japan, China\n\nGraduate School of Peking Union Medical College\nChinese Academy of Medical Sciences\nPeking Union Medical College\nBeijingChina\n\nNational Center for Respiratory Medicine\nBeijingChina\n\nInstitute of Respiratory Medicine, Chinese Academy of Medical Sciences\nBeijingChina\n\nNational Clinical Research Center for Respiratory Diseases\nBeijingChina\n\n\nCentre Hospitalier Universitaire Vaudois (CHUV)\nUniversità Cattolica del Sacro Cuore\nItaly, Switzerland Hong Zhang \nDepartment of Laboratory\nShenyang Chest Hospital\nShenyangChina\n\nYinghui Fu \nInstitute of Respiratory Diseases\nShenyang Chest Hospital\nShenyangChina\n\nYongyu Liu \nInstitute of Respiratory Diseases\nShenyang Chest Hospital\nShenyangChina\n\nGang Hou \nDepartment of Pulmonary and Critical Care Medicine\nCenter of Respiratory Medicine\nFriendship Hospital\nBeijingChina-Japan, China\n\nGraduate School of Peking Union Medical College\nChinese Academy of Medical Sciences\nPeking Union Medical College\nBeijingChina\n\nNational Center for Respiratory Medicine\nBeijingChina\n\nInstitute of Respiratory Medicine, Chinese Academy of Medical Sciences\nBeijingChina\n\nNational Clinical Research Center for Respiratory Diseases\nBeijingChina\n\n\nCentre Hospitalier Universitaire Vaudois (CHUV)\nUniversità Cattolica del Sacro Cuore\nItaly, Switzerland\n\n\nNanjing Medical University\nChina\n\nCitation: Diagnostic Efficacy of Xpert MTB/RIF Assay in Bronchoalveolar Lavage Fluid for Tracheobronchial Tuberculosis: A Retrospective Analysis Frontiers in Medicine | www.frontiersin.org\n1682107August 202110.3389/fmed.2021.682107Received: 17 March 2021 Accepted: 12 July 2021ORIGINAL RESEARCH Edited by: Reviewed by: *Correspondence: Gang Hou hougangcmu@163.com Yongyu Liu L24315516@sina.com † These authors have contributed equally to this work Specialty section: This article was submitted to Pulmonary Medicine, a section of the journal Frontiers in Medicine (2021) Diagnostic Efficacy of Xpert MTB/RIF Assay in Bronchoalveolar Lavage Fluid for Tracheobronchial Tuberculosis: A Retrospective Analysis. Front. Med. 8:682107.Xpert MTB/RIFtracheobronchial tuberculosisbronchoalveolar lavagediagnosisMycobacterium tuberculosis\nBackground: The Xpert Mycobacterium tuberculosis/rifampin (MTB/RIF) assay has shown good diagnostic efficacy in brushing and biopsy tissue samples from patients with tracheobronchial tuberculosis (TBTB). However, its diagnostic value in bronchoalveolar lavage fluid (BALF) is still unclear. Therefore, the present retrospective study aimed to evaluate the diagnostic value of the Xpert MTB/RIF assay in BALF.Methods:The clinical data of 266 patients with suspected TBTB from January 2018 to October 2020 were pooled with complete details of bronchial brush and bronchoalveolar lavage samples. Smears of the bronchial brushings were stained with Auramine O stain to detect acid-fast bacilli (AFB), and BALF samples were used for culturing MTB with the BACTEC MGIT 960 system and the Xpert MTB/RIF assay. The diagnostic performance of these methods was assessed and compared.Results: A total of 266 patients suspected to have TBTB were enrolled in the final analysis. Of these patients, 179 patients were confirmed to have TBTB and 87 patients were non-TBTB. The sensitivity of the Xpert MTB/RIF assay in BALF (87.2%) was significantly higher than that of the brush smear for AFB (35.2%, p < 0.001). No significant difference was observed between the sensitivities of the Xpert MTB/RIF assay in BALF and MTB culture in BALF (87.2 vs. 84.9%, p = 0.542). The specificities of the Xpert MTB/RIF assay in BALF, MTB culture in BALF, and the bronchial brush smear were 97.7, 97.7, and 98.9%, respectively. The positive predictive value (PPV) and negative predictive value (NPV) of the Xpert MTB/RIF assay in BALF, MTB culture in BALF, and the bronchial brush smear were 98.7 and 78.7%, 98.7 and 75.9%, and 98.4 and 42.6%, respectively. Among the MTB culture-positive patients with TBTB detected by the Xpert assay, 27.0% (20/74) were identified to be resistant to RIF. Sun et al.Diagnostic Efficacy of Xpert MTB/RIFConclusions: The Xpert MTB/RIF assay in BALF enables a rapid and accurate diagnosis of TBTB and identification of RIF resistance, which is crucial for timely and proper treatment. Moreover, in patients with TBTB, BALF could be used as an alternative to bronchial brushing and biopsy tissues for the Xpert MTB/RIF assay. INTRODUCTION\n\nTuberculosis (TB) is considered to be the ninth leading cause of death worldwide, and it remains one of the major global public health issues (1). Tracheobronchial tuberculosis (TBTB) is a special form of TB and is defined as Mycobacterium tuberculosis (MTB) infection of the tracheobronchial tree with microbial and histopathological evidence, regardless of parenchymal involvement (2). TBTB has been reported in approximately 4.1-54.3% of patients with active pulmonary TB (3,4). Severe tracheobronchial stenosis caused by TBTB, which affects the patient\'s quality of life, was detected in 23.3% of patients with TBTB (5). The diagnosis of TBTB is, however, challenging because of its non-specific clinical manifestations, especially in the early stage, and unsatisfactory existing methods for acquiring microbial evidence. Thus, patients with TBTB often face a dilemma of delayed diagnosis and untimely treatment, which result in the occurrence and progression of severe tracheobronchial stenosis (6)(7)(8). Therefore, the rapid and accurate diagnosis of TBTB is crucial to minimize or prevent complications. The Xpert MTB/rifampin (MTB/RIF) assay (Cepheid, Sunnyvale, CA, USA) is an integrated semiautomated nucleic acid amplification test designed for rapid detection of the presence of MTB and mutations associated with RIF resistance within 2 h (9). Several previous studies have proved the diagnostic value of bronchoalveolar lavage fluid (BALF) for the Xpert MTB/RIF assay in adults and children with pulmonary TB (10)(11)(12). However, because TBTB is a special type of pulmonary TB, the efficacy of its diagnosis by using different methods varies from that for pulmonary TB and even among different subtypes of TBTB because of the different characteristics of exudation, proliferation, and necrosis. Our previous study (13) showed that the sensitivities of the Xpert MTB/RIF assay of bronchial brushing and biopsy samples from TBTB patients were 57. 4 and 63.9%, respectively, and the specificity for both types of samples was 100%; this proved that these results were superior to those of sputum smears, bronchial brush smears, and sputum culture. The yield of the Xpert MTB/RIF assay in bronchial brushings was significantly higher for the caseating or ulcerative subtypes than for the fibrostenotic or edematous-hyperemic subtypes (13). Bronchial biopsy and brushing samples may not be available for diagnosing bronchial fibrous stenosis and other conditions; however, in most TBTB cases, BALF is available and is a relatively less invasive and safer method. Hence, it is necessary to evaluate the diagnostic performance of the Xpert MTB/RIF assay in BALF for TBTB patients, and more specifically, to determine the diagnostic performance of the assay for different TBTB bronchoscopic subtypes. Therefore, we conducted this retrospective study to evaluate the efficacy of the Xpert MTB/RIF assay in BALF for the rapid diagnosis of TBTB. MATERIALS AND METHODS\n\n\nParticipants\n\nThis was a retrospective study conducted in the First Hospital of China Medical University and Shenyang Chest Hospital from Janurary 2018 to October 2020.\n\nA total of 266 suspected TBTB patients were enrolled in the study through the inpatient case registration system in the hospital information system. Inclusion criteria were as follows:\n\n(1) inpatient cases suspected to have TBTB who were registered in the hospital information system and were available for followup after 6 months and (2) patients who underwent bronchial brush and bronchoalveolar lavage sample collection. Brushing specimens were used for smears for acid-fast bacilli (AFB), while BALF samples were used for MTB culture and the Xpert MTB/RIF assay. Exclusion criteria were as follows: (1) patients without a definite diagnosis after discharge from the hospital and after 6 months of follow-up and (2) patients with obvious pulmonary involvement instead of TBTB alone.\n\nDefinition: TBTB was confirmed by the presence of a visible tracheobronchial lesion proximal to a segmental bronchus, with histological evidence from bronchial biopsy and/or microbiological tests (sputum smear or brushing smear or BALF was positive for AFB or MTB culture was positive) (5,14). Definition: TBTB was confirmed by the presence of a visible tracheobronchial lesion proximal to a segmental bronchus, with histological evidence from bronchial biopsy and/or microbiological tests (sputum smear or brushing smear or BALF was positive for AFB or MTB culture was positive) (5,14).\n\nClinical data of the patients were collected by two authors (YS and QinZ) from the medical databases of the hospitals. The study was approved by the Ethics Committee of China Medical University and Shenyang Chest Hospital. The ethics committee exempted obtaining informed consent from patients because of the retrospective nature of the study. Patient data were deidentified before data access and analysis.\n\n\nAFB Smear Microscopy\n\nThree bronchial brush smears were sent to the clinical microbiology laboratory for staining directly with rapid Auramine O fluorescent stain (AO stain, Ourchem, Sinopharm Chemical Reagent Co. Ltd., Shanghai, China) for detecting AFB by microscopy (15). Sputum for AFB detection was also collected during the hospitalization. The sample was considered AFB-positive if AFB was detected in at least one bronchial brush or sputum smear microscopy.\n\n\nBALF AFB Smear Microscopy\n\nThree bronchial brush smears were sent to the clinical microbiology laboratory for staining directly with rapid Auramine O fluorescent stain (AO stain, Ourchem, Sinopharm Chemical Reagent Co. Ltd., Shanghai, China) for detecting AFB by microscopy (15). Sputum for AFB detection was also collected during the hospitalization. The sample was considered AFB-positive if AFB was detected in at least one bronchial brush or sputum smear microscopy.\n\n\nBALF\n\nAll patients were assessed with an Olympus electronic bronchoscopy system (1T260, Tokyo, Japan). The bronchoscopy findings revealed that TBTB showed highly variable tracheobronchial appearance, and it was classified into seven subtypes according to pathological changes reported by Chung et al. (16): actively caseating, edematous-hyperemic, fibrostenotic, tumorous, granular, ulcerative, and non-specific bronchitis type. Bronchoalveolar lavage was obtained directly from the lesion location. The total amount of 37 • C saline, approximately 100 mL, was injected in equal doses, 20 mL in each dose, and finally, the lavage fluid was immediately recovered by vacuum suction (−100∼-150 mmHg).\n\n\nMTB Culture and Drug Sensitivity Test MTB Culture and Drug Sensitivity Test\n\nBALF specimens and sputum were processed using the BACTEC MGIT 960 rapid system (Becton Dickinson, Oxford, UK) for MTB culture (17). If the MTB culture was positive, the drug sensitivity was automatically tested through the BACTEC MGIT 960 SIRE kit (Becton Dickinson) (17).\n\n\nXpert MTB/RIF Assay\n\nFive milliliters of BALF specimen were taken and mixed evenly with a sample reagent buffer (SR) (containing sodium hydroxide and isopropanol) in the ratio of 2:1. The mixture was left to stand at room temperature for 15 min and then transferred to the MTB/RIF detection kit (Cepheid, USA). The reaction box was placed in the Gene Xpert instrument (Cepheid) for detection. The Xpert MTB/RIF assay has been designed to detect MTB and also mutations that confer resistance to rifampicin by using three specific primers and five unique molecular probes that target the 81-bp core region of the bacterial RNA polymerase β subunit (rpoB) gene (18)(19)(20).\n\n\nStatistical Analysis Five milliliters of BALF specimen were taken and mixed evenly with a sample reagent buffer (SR) (containing sodium hydroxide and isopropanol) in the ratio of 2:1. The mixture was left to stand at room temperature for 15 min and then transferred to the MTB/RIF detection kit (Cepheid, USA). The reaction box was placed in the Gene Xpert instrument (Cepheid) for detection. The Xpert MTB/RIF assay has been designed to detect MTB and also mutations that confer resistance to rifampicin by using three specific primers and five unique molecular probes that target the 81-bp core region of the bacterial RNA polymerase β subunit (rpoB) gene (18)(19)(20).\n\n\nStatistical Analysis\n\nIBM SPSS version 20.0 software (SPSS Inc., Chicago, IL, USA) was used for the statistical analysis. The sensitivity, specificity, positive predictive value (PPV), and negative predictive value (NPV) of the different diagnostic methods were calculated with two-sided 95% confidence intervals (CIs). The diagnostic performance of the different diagnostic methods for various bronchial subtypes was compared with chi-square tests. A P-value of <0.05 was considered to be statistically significant.\n\n\nRESULTS\n\n\nPatient Characteristics RESULTS\n\n\nPatient Characteristics\n\nA total of 266 patients (155 males and 111 females) were included in the final analysis. Of these 266 patients, 179 patients were diagnosed to have TBTB. The age of the patients ranged from 13 to 91 years (mean age: 44.8 years) ( Table 1). The diagnostic yield of the different diagnostic methods is shown in Table 1. The details of the remaining 87 patients with non-TBTB are also provided in Table 1. The diagnostic yield of the Xpert MTB/RIF assay in different specimens obtained from TBTB patients is shown in Supplementary Table. As Table 1 shown, 87 cases were found to be other diagnosis among people suspected of having TBTB since in the differential diagnosis. Among the patients of TBTB, as for one of the initial treatment options in our patient, totally 89 patients underwent therapeutic bronchoscopy. Under bronchoscopy, if there was caseating necrosis or granular nodules or mucosal congestion and edema, cryotherapy via bronchoscope was performed; while if there was fibrous stenosis, balloon dilatation via bronchoscope was performed. None of the patients in this study received corticosteroid therapy for TBTB.\n\n\nDiagnostic Efficacy of Conventional Techniques and the Xpert MTB/RIF Assay in BALF for TBTB Diagnostic Efficacy of Conventional Techniques and the Xpert MTB/RIF Assay in BALF for TBTB\n\nThe diagnostic performance of the conventional techniques and the Xpert MTB/RIF assay in BALF for TBTB is shown in  Table 2). The sensitivity and NPV of the Xpert MTB/RIF assay in BALF were significantly higher than those of bronchial brush smear microscopy (χ 2 = 101.716, p < 0.001; χ 2 = 37.141, p < 0.001) ( Table 2). No difference in sensitivity was observed between the Xpert MTB/RIF assay and MTB culture in BALF (χ 2 = 0.372, p = 0.542) ( Table 2). \n\n\nComparison of Diagnostic Consistency of the Different Diagnostic Techniques\n\nThe diagnostic consistencies of the three different diagnostic techniques were compared (  Table 4). The tumorous and ulcerative subtypes were not included because our sample contained only three cases of these subtypes. The diagnostic rate of the Xpert MTB/RIF assay in BALF for the actively caseating subtype was significantly higher than that for the fibrostenotic subtype (χ 2 = 5.671, p = 0.030) ( Table 4). Moreover, the diagnostic rate of the Xpert MTB/RIF assay in BALF for the non-specific bronchitic subtype was significantly lower than that for the actively caseating subtype (χ 2 = 12.443, p < 0.001) or for the edematous-hyperemic subtype (χ 2 = 6.992, p = 0.008) ( Table 4). The diagnostic consistencies of the three different diagnostic techniques were compared (  Table 4). The tumorous and ulcerative subtypes were not included because our sample contained only three cases of these subtypes. The diagnostic rate of the Xpert MTB/RIF assay in BALF for the actively caseating subtype was significantly higher than that for the fibrostenotic subtype (χ 2 = 5.671, p = 0.030) ( Table 4). Moreover, the diagnostic rate of the Xpert MTB/RIF assay in BALF for the non-specific bronchitic subtype was significantly lower than that for the actively caseating subtype (χ 2 = 12.443, p < 0.001) or for the edematous-hyperemic subtype (χ 2 = 6.992, p = 0.008) ( Table 4). \n\n\nDISCUSSION\n\nThe diagnosis and treatment of TBTB are often delayed, resulting in the development of bronchial stenosis. Therefore, a timely and accurate diagnosis of TBTB is critical. Bronchoalveolar lavage is a less invasive and technically easy method for diagnosis. In our present study, we found that the diagnostic efficacy of the Xpert MTB/RIF assay in BALF was similar to that of the MTB culture in BALF but much faster for the initiation of the treatment. To date, sputum smear examination for AFB is considered to be a popular and rapid bacteriological examination method for diagnosing TBTB. However, it is worth noting that more than one-third of TBTB patients have negative sputum smears (21,22), which is similar to the result of our present study (the negative smear rate was 63.1%). The bronchial brush smear also did not show satisfactory results; the detection rate was 35.2% for TBTB, similar to that reported in previous studies (23), which indicated the limited improvement in diagnosis efficacy. Although MTB culture is considered as the gold standard for diagnosing TB, it usually takes 2-8 weeks to produce results, while the Xpert MTB/RIF assay is less time-consuming (24). This retrospective study showed that the sensitivity of the Xpert MTB/RIF assay did not differ from that of MTB culture in BALF for diagnosing TBTB. The sensitivity and specificity of the GeneXpert system for diagnosing TB in an intermediate burden city were reported to be 80 and 98%, respectively (25). The PPV and NPV of the test were 92.3 and 95.1%, respectively. Therefore, the Xpert MTB/RIF assay can accurately detect MTB in BALF and prevent complications of bronchial stenosis more rapidly by enabling early proper treatment. In our previous study (13), the Xpert MTB/RIF assay was performed on samples of bronchial brush and biopsy tissues from TBTB patients. The sensitivity of the Xpert MTB/RIF assay in BALF for TBTB patients was 87.2%, which was higher than that for bronchial brush samples (57.4%; χ 2 = 24.822, p = 0.000), while the sensitivity of the Xpert MTB/RIF assay in BALF for TBTB was higher than that of the Xpert MTB/RIF assay in biopsy tissue in our previous study (63.9%, χ 2 = 16.097, p = 0.000) (Supplementary Table). The comparison of the sensitivity, specificity, NPV, and PPV showed

In [ ]:
# attributes_csv = starter_data + "/final.csv"
# attributes_df = pd.read_csv(attributes_csv)
# attributes_df.head(10)

,Unnamed: 0,corpusid,externalids,url,title,authors,venue,publicationvenueid,year,referencecount,citationcount,influentialcitationcount,isopenaccess,s2fieldsofstudy,publicationtypes,publicationdate,journal,updated,id
0,0,52273203,"{""ACL"": null, ""DBLP"": null, ""ArXiv"": null, ""MA...",https://www.semanticscholar.org/paper/39063bcd...,Large conformational changes of a highly dynam...,"{""{\""authorId\"": \""51285510\"", \""name\"": \""Isa...",Communications Biology,069e05e7-ca35-41d0-a8c7-bdc9ec6a82af,2018.0,28,13,0,True,"{""{\""category\"": \""Biology\"", \""source\"": \""s2...",{JournalArticle},2018-09-03,"{""name"": ""Communications Biology"", ""pages"": nu...",2023-03-31T01:28:37.897Z,5692596
1,1,23708908,"{""ACL"": null, ""DBLP"": null, ""ArXiv"": null, ""MA...",https://www.semanticscholar.org/paper/6ec7c156...,Drug sensitivity profiling identifies potentia...,"{""{\""authorId\"": \""5699001\"", \""name\"": \""H. K...",OncoTarget,106ecc86-1801-4b36-a05c-d36db69a968c,2017.0,46,24,0,True,"{""{\""category\"": \""Biology\"", \""source\"": \""s2...",{JournalArticle},2017-10-31,"{""name"": ""Oncotarget"", ""pages"": ""97516 - 97527...",2023-04-05T06:18:15.837Z,5692609
2,2,13232625,"{""ACL"": null, ""DBLP"": null, ""ArXiv"": null, ""MA...",https://www.semanticscholar.org/paper/c8566272...,Men's memory for women's sexual-interest and r...,"{""{\""authorId\"": \""4425040\"", \""name\"": \""T. T...",NaN,NaN,2011.0,36,13,0,True,"{""{\""category\"": \""Psychology\"", \""source\"": \...",{Review},2011-09-01,"{""name"": ""Applied Cognitive Psychology"", ""page...",2023-04-05T08:18:02.240Z,5692611
3,3,73484844,"{""ACL"": null, ""DBLP"": null, ""ArXiv"": null, ""MA...",https://www.semanticscholar.org/paper/d4c9b2fa...,The Reactive Plasticity of Hippocampal Ionotro...,"{""{\""authorId\"": \""2225106\"", \""name\"": \""A. M...",International Journal of Molecular Sciences,8506a01a-40b8-4e6f-bbb8-ce2492139c15,2019.0,97,15,1,True,"{""{\""category\"": \""Biology\"", \""source\"": \""s2...","{Review,JournalArticle}",2019-02-27,"{""name"": ""International Journal of Molecular S...",2023-05-20T17:20:54.230Z,5692615
4,4,229159752,"{""ACL"": null, ""DBLP"": null, ""ArXiv"": null, ""MA...",https://www.semanticscholar.org/paper/7f13abe2...,High Mortality Rate in Adult COVID-19 Inpatien...,"{""{\""authorId\"": \""7685173\"", \""name\"": \""Saee...",Journal of Multidisciplinary Healthcare,12e5e550-28bd-401c-a348-f347956deec4,2020.0,37,17,1,True,"{""{\""category\"": \""Medicine\"", \""source\"": \""s...","{JournalArticle,Review}",2020-12-01,"{""name"": ""Journal of Multidisciplinary Healthc...",2023-05-23T13:34:07.581Z,5692620
5,5,10041098,"{""ACL"": null, ""DBLP"": null, ""ArXiv"": null, ""MA...",https://www.semanticscholar.org/paper/92b26dee...,NADH-dependent metabolism of nitric oxide in a...,"{""{\""authorId\"": \""1792255\"", \""name\"": \""A. I...",Planta,66507f0b-12a1-4058-a35c-73029853d5b9,2004.0,30,145,3,False,"{""{\""category\"": \""Biology\"", \""source\"": \""s2...",{JournalArticle},2004-01-22,"{""name"": ""Planta"", ""pages"": ""95-102"", ""volume""...",2023-04-05T15:01:41.273Z,5692625
6,6,19472375,"{""ACL"": null, ""DBLP"": null, ""ArXiv"": null, ""MA...",https://www.semanticscholar.org/paper/2c682757...,Aspects of posttraumatic stress disorder in lo...,"{""{\""authorId\"": \""2000616\"", \""name\"": \""A. D...",Journal of cancer survivorship,649b7693-cb10-4892-b8a2-65b9b51fcd50,2016.0,33,18,0,False,"{""{\""category\"": \""Psychology\"", \""source\"": \...",{JournalArticle},2016-02-26,"{""name"": ""Journal of Cancer Survivorship"", ""pa...",2023-04-05T19:07:12.948Z,5692626
7,7,219603447,"{""ACL"": null, ""DBLP"": null, ""ArXiv"": null, ""MA...",https://www.semanticscholar.org/paper/9b9659a4...,Multicenter assessment of the Brain Injury Gui...,"{""{\""authorId\"": \""145776250\"", \""name\"": \""Ab...",Trauma Surgery & Acute Care Open,d40f33e8-6f79-4e91-a62e-acf29f9a3e2f,2020.0,35,11,0,True,"{""{\""category\"": \""Medicine\"", \""source\"": \""s...","{JournalArticle,Review}",2020-05-01,"{""name"": ""Trauma Surgery & Acute Care Open"", ""...",2023-04-07T01:56:26.282Z,5692637
8,8,15826244,"{""ACL"": null, ""DBLP"": null, ""ArXiv"": null, ""MA...",https://www.semanticscholar.org/paper/314f8d8a...,Mycobacterium haemophilum as the Initial Prese...,"{""{\""authorId\"": \""2060804071\"", \""name\"": \""T...",Case Reports in Rheumatology,884ab217-3965-4a74-90d1-003d0b378d6d,2014.0,24,8,0,True,"{""{\""category\"": \""Medicine\"", \""source\"": \""s...",{JournalArticle},2014-01-12,"{""name"": ""Case Reports in Rheumatology"", ""page...",2023-04-07T01:15:17.667Z,5692638
9,9,2311509,"{""ACL"": null, ""DBLP"": null, ""ArXiv"": null, ""MA...",https://www.semanticscholar.org/paper/7a0b4601...,Up-regulation and subcellular localization of ...,"{""{\""authorId\"": \""14726800\"", \""name\"": \""Hua...",BMC Cancer,b482a99f-ef53-4694-aec6-32ad78e0d716,2010.0,58,44,0,True,"{""{\""category\"": \""Biology\"", \""source\"": \""s2...",{JournalArticle},2010-07-06,"{""name"": ""BMC Cancer"", ""pages"": ""356 - 356"", ""...",2023-04-07T01:28:15.493Z,5692639

In [20]:
openai_api_key = keys["openai"]

llm = OpenAI(temperature=0.5, openai_api_key=openai_api_key)

text_splitter = CharacterTextSplitter(chunk_size=2000, chunk_overlap=0)

In [23]:
seperated_text.get('documents')

['Citation: Diagnostic Efficacy of Xpert MTB/RIF Assay in Bronchoalveolar Lavage Fluid for Tracheobronchial Tuberculosis: A Retrospective Analysis\nAugust 2021\n\nPiero Valentini \nJesica Mazza-Stalder \nQiao Liu \nSun Y \nZhang Q \nZhang Q \nLiu C \nZhang H Fu \nY Liu \nY \nHou G \nYue Sun \nInstitute of Respiratory Diseases\nThe First Hospital of China Medical University\nShenyangChina\n\n† \nQing Zhang \nDepartment of Endoscopy\nShenyang Chest Hospital\nShenyangChina\n\n† \nQin Zhang \nInstitute of Respiratory Diseases\nThe First Hospital of China Medical University\nShenyangChina\n\nChang Liu \nDepartment of Endoscopy\nShenyang Chest Hospital\nShenyangChina\n\nHong Zhang \nDepartment of Laboratory\nShenyang Chest Hospital\nShenyangChina\n\nYinghui Fu \nInstitute of Respiratory Diseases\nShenyang Chest Hospital\nShenyangChina\n\nYongyu Liu \nInstitute of Respiratory Diseases\nShenyang Chest Hospital\nShenyangChina\n\nGang Hou \nDepartment of Pulmonary and Critical Care Medicine\nCenter of Respiratory Medicine\nFriendship Hospital\nBeijingChina-Japan, China\n\nGraduate School of Peking Union Medical College\nChinese Academy of Medical Sciences\nPeking Union Medical College\nBeijingChina\n\nNational Center for Respiratory Medicine\nBeijingChina\n\nInstitute of Respiratory Medicine, Chinese Academy of Medical Sciences\nBeijingChina\n\nNational Clinical Research Center for Respiratory Diseases\nBeijingChina\n\n\nCentre Hospitalier Universitaire Vaudois (CHUV)\nUniversità Cattolica del Sacro Cuore\nItaly, Switzerland',
 'Hong Zhang \nDepartment of Laboratory\nShenyang Chest Hospital\nShenyangChina\n\nYinghui Fu \nInstitute of Respiratory Diseases\nShenyang Chest Hospital\nShenyangChina\n\nYongyu Liu \nInstitute of Respiratory Diseases\nShenyang Chest Hospital\nShenyangChina\n\nGang Hou \nDepartment of Pulmonary and Critical Care Medicine\nCenter of Respiratory Medicine\nFriendship Hospital\nBeijingChina-Japan, China\n\nGraduate School of Peking Union Medical College\nChinese Academy of Medical Sciences\nPeking Union Medical College\nBeijingChina\n\nNational Center for Respiratory Medicine\nBeijingChina\n\nInstitute of Respiratory Medicine, Chinese Academy of Medical Sciences\nBeijingChina\n\nNational Clinical Research Center for Respiratory Diseases\nBeijingChina\n\n\nCentre Hospitalier Universitaire Vaudois (CHUV)\nUniversità Cattolica del Sacro Cuore\nItaly, Switzerland\n\n\nNanjing Medical University\nChina\n\nCitation: Diagnostic Efficacy of Xpert MTB/RIF Assay in Bronchoalveolar Lavage Fluid for Tracheobronchial Tuberculosis: A Retrospective Analysis',
 'Frontiers in Medicine | www.frontiersin.org\n1682107August 202110.3389/fmed.2021.682107Received: 17 March 2021 Accepted: 12 July 2021ORIGINAL RESEARCH Edited by: Reviewed by: *Correspondence: Gang Hou hougangcmu@163.com Yongyu Liu L24315516@sina.com † These authors have contributed equally to this work Specialty section: This article was submitted to Pulmonary Medicine, a section of the journal Frontiers in Medicine (2021) Diagnostic Efficacy of Xpert MTB/RIF Assay in Bronchoalveolar Lavage Fluid for Tracheobronchial Tuberculosis: A Retrospective Analysis. Front. Med. 8:682107.Xpert MTB/RIFtracheobronchial tuberculosisbronchoalveolar lavagediagnosisMycobacterium tuberculosis\nBackground: The Xpert Mycobacterium tuberculosis/rifampin (MTB/RIF) assay has shown good diagnostic efficacy in brushing and biopsy tissue samples from patients with tracheobronchial tuberculosis (TBTB). However, its diagnostic value in bronchoalveolar lavage fluid (BALF) is still unclear. Therefore, the present retrospective study aimed to evaluate the diagnostic value of the Xpert MTB/RIF assay in BALF.Methods:The clinical data of 266 patients with suspected TBTB from January 2018 to October 2020 were pooled with complete details of bronchial brush and bronchoalveolar lavage samples. Smears of the bronchial brushings were stained with Auramine O stain to detect acid-fast bacilli (AFB), and BALF samples were used for culturing MTB with the BACTEC MGIT 960 system and the Xpert MTB/RIF assay. The diagnostic performance of these methods was assessed and compared.Results: A total of 266 patients suspected to have TBTB were enrolled in the final analysis. Of these patients, 179 patients were confirmed to have TBTB and 87 patients were non-TBTB. The sensitivity of the Xpert MTB/RIF assay in BALF (87.2%) was significantly higher than that of the brush smear for AFB (35.2%, p < 0.001). No significant difference was observed between the sensitivities of the Xpert MTB/RIF assay in BALF and MTB culture in BALF (87.2 vs. 84.9%, p = 0.542). The specificities of the Xpert MTB/RIF assay in BALF, MTB culture in BALF, and the bronchial brush smear were 97.7, 97.7, and 98.9%, respectively. The positive predictive value (PPV) and negative predictive value (NPV) of the Xpert MTB/RIF assay in BALF, MTB culture in BALF, and the bronchial brush smear were 98.7 and 78.7%, 98.7 and 75.9%, and 98.4 and 42.6%, respectively. Among the MTB culture-positive patients with TBTB detected by the Xpert assay, 27.0% (20/74) were identified to be resistant to RIF. Sun et al.Diagnostic Efficacy of Xpert MTB/RIFConclusions: The Xpert MTB/RIF assay in BALF enables a rapid and accurate diagnosis of TBTB and identification of RIF resistance, which is crucial for timely and proper treatment. Moreover, in patients with TBTB, BALF could be used as an alternative to bronchial brushing and biopsy tissues for the Xpert MTB/RIF assay.',
 "INTRODUCTION\n\nTuberculosis (TB) is considered to be the ninth leading cause of death worldwide, and it remains one of the major global public health issues (1). Tracheobronchial tuberculosis (TBTB) is a special form of TB and is defined as Mycobacterium tuberculosis (MTB) infection of the tracheobronchial tree with microbial and histopathological evidence, regardless of parenchymal involvement (2). TBTB has been reported in approximately 4.1-54.3% of patients with active pulmonary TB (3,4). Severe tracheobronchial stenosis caused by TBTB, which affects the patient's quality of life, was detected in 23.3% of patients with TBTB (5). The diagnosis of TBTB is, however, challenging because of its non-specific clinical manifestations, especially in the early stage, and unsatisfactory existing methods for acquiring microbial evidence. Thus, patients with TBTB often face a dilemma of delayed diagnosis and untimely treatment, which result in the occurrence and progression of severe tracheobronchial stenosis (6)(7)(8). Therefore, the rapid and accurate diagnosis of TBTB is crucial to minimize or prevent complications.",
 'The Xpert MTB/rifampin (MTB/RIF) assay (Cepheid, Sunnyvale, CA, USA) is an integrated semiautomated nucleic acid amplification test designed for rapid detection of the presence of MTB and mutations associated with RIF resistance within 2 h (9). Several previous studies have proved the diagnostic value of bronchoalveolar lavage fluid (BALF) for the Xpert MTB/RIF assay in adults and children with pulmonary TB (10)(11)(12). However, because TBTB is a special type of pulmonary TB, the efficacy of its diagnosis by using different methods varies from that for pulmonary TB and even among different subtypes of TBTB because of the different characteristics of exudation, proliferation, and necrosis. Our previous study (13) showed that the sensitivities of the Xpert MTB/RIF assay of bronchial brushing and biopsy samples from TBTB patients were 57. 4 and 63.9%, respectively, and the specificity for both types of samples was 100%; this proved that these results were superior to those of sputum smears, bronchial brush smears, and sputum culture. The yield of the Xpert MTB/RIF assay in bronchial brushings was significantly higher for the caseating or ulcerative subtypes than for the fibrostenotic or edematous-hyperemic subtypes (13). Bronchial biopsy and brushing samples may not be available for diagnosing bronchial fibrous stenosis and other conditions; however, in most TBTB cases, BALF is available and is a relatively less invasive and safer method. Hence, it is necessary to evaluate the diagnostic performance of the Xpert MTB/RIF assay in BALF for TBTB patients, and more specifically, to determine the diagnostic performance of the assay for different TBTB bronchoscopic subtypes. Therefore, we conducted this retrospective study to evaluate the efficacy of the Xpert MTB/RIF assay in BALF for the rapid diagnosis of TBTB.',
 'MATERIALS AND METHODS\n\n\nParticipants\n\nThis was a retrospective study conducted in the First Hospital of China Medical University and Shenyang Chest Hospital from Janurary 2018 to October 2020.\n\nA total of 266 suspected TBTB patients were enrolled in the study through the inpatient case registration system in the hospital information system. Inclusion criteria were as follows:\n\n(1) inpatient cases suspected to have TBTB who were registered in the hospital information system and were available for followup after 6 months and (2) patients who underwent bronchial brush and bronchoalveolar lavage sample collection. Brushing specimens were used for smears for acid-fast bacilli (AFB), while BALF samples were used for MTB culture and the Xpert MTB/RIF assay. Exclusion criteria were as follows: (1) patients without a definite diagnosis after discharge from the hospital and after 6 months of follow-up and (2) patients with obvious pulmonary involvement instead of TBTB alone.\n\nDefinition: TBTB was confirmed by the presence of a visible tracheobronchial lesion proximal to a segmental bronchus, with histological evidence from bronchial biopsy and/or microbiological tests (sputum smear or brushing smear or BALF was positive for AFB or MTB culture was positive) (5,14).',
 'Definition: TBTB was confirmed by the presence of a visible tracheobronchial lesion proximal to a segmental bronchus, with histological evidence from bronchial biopsy and/or microbiological tests (sputum smear or brushing smear or BALF was positive for AFB or MTB culture was positive) (5,14).\n\nClinical data of the patients were collected by two authors (YS and QinZ) from the medical databases of the hospitals. The study was approved by the Ethics Committee of China Medical University and Shenyang Chest Hospital. The ethics committee exempted obtaining informed consent from patients because of the retrospective nature of the study. Patient data were deidentified before data access and analysis.\n\n\nAFB Smear Microscopy\n\nThree bronchial brush smears were sent to the clinical microbiology laboratory for staining directly with rapid Auramine O fluorescent stain (AO stain, Ourchem, Sinopharm Chemical Reagent Co. Ltd., Shanghai, China) for detecting AFB by microscopy (15). Sputum for AFB detection was also collected during the hospitalization. The sample was considered AFB-positive if AFB was detected in at least one bronchial brush or sputum smear microscopy.\n\n\nBALF',
 'AFB Smear Microscopy\n\nThree bronchial brush smears were sent to the clinical microbiology laboratory for staining directly with rapid Auramine O fluorescent stain (AO stain, Ourchem, Sinopharm Chemical Reagent Co. Ltd., Shanghai, China) for detecting AFB by microscopy (15). Sputum for AFB detection was also collected during the hospitalization. The sample was considered AFB-positive if AFB was detected in at least one bronchial brush or sputum smear microscopy.\n\n\nBALF\n\nAll patients were assessed with an Olympus electronic bronchoscopy system (1T260, Tokyo, Japan). The bronchoscopy findings revealed that TBTB showed highly variable tracheobronchial appearance, and it was classified into seven subtypes according to pathological changes reported by Chung et al. (16): actively caseating, edematous-hyperemic, fibrostenotic, tumorous, granular, ulcerative, and non-specific bronchitis type. Bronchoalveolar lavage was obtained directly from the lesion location. The total amount of 37 • C saline, approximately 100 mL, was injected in equal doses, 20 mL in each dose, and finally, the lavage fluid was immediately recovered by vacuum suction (−100∼-150 mmHg).\n\n\nMTB Culture and Drug Sensitivity Test',
 'MTB Culture and Drug Sensitivity Test\n\nBALF specimens and sputum were processed using the BACTEC MGIT 960 rapid system (Becton Dickinson, Oxford, UK) for MTB culture (17). If the MTB culture was positive, the drug sensitivity was automatically tested through the BACTEC MGIT 960 SIRE kit (Becton Dickinson) (17).\n\n\nXpert MTB/RIF Assay\n\nFive milliliters of BALF specimen were taken and mixed evenly with a sample reagent buffer (SR) (containing sodium hydroxide and isopropanol) in the ratio of 2:1. The mixture was left to stand at room temperature for 15 min and then transferred to the MTB/RIF detection kit (Cepheid, USA). The reaction box was placed in the Gene Xpert instrument (Cepheid) for detection. The Xpert MTB/RIF assay has been designed to detect MTB and also mutations that confer resistance to rifampicin by using three specific primers and five unique molecular probes that target the 81-bp core region of the bacterial RNA polymerase β subunit (rpoB) gene (18)(19)(20).\n\n\nStatistical Analysis',
 'Five milliliters of BALF specimen were taken and mixed evenly with a sample reagent buffer (SR) (containing sodium hydroxide and isopropanol) in the ratio of 2:1. The mixture was left to stand at room temperature for 15 min and then transferred to the MTB/RIF detection kit (Cepheid, USA). The reaction box was placed in the Gene Xpert instrument (Cepheid) for detection. The Xpert MTB/RIF assay has been designed to detect MTB and also mutations that confer resistance to rifampicin by using three specific primers and five unique molecular probes that target the 81-bp core region of the bacterial RNA polymerase β subunit (rpoB) gene (18)(19)(20).\n\n\nStatistical Analysis\n\nIBM SPSS version 20.0 software (SPSS Inc., Chicago, IL, USA) was used for the statistical analysis. The sensitivity, specificity, positive predictive value (PPV), and negative predictive value (NPV) of the different diagnostic methods were calculated with two-sided 95% confidence intervals (CIs). The diagnostic performance of the different diagnostic methods for various bronchial subtypes was compared with chi-square tests. A P-value of <0.05 was considered to be statistically significant.\n\n\nRESULTS\n\n\nPatient Characteristics',
 'RESULTS\n\n\nPatient Characteristics\n\nA total of 266 patients (155 males and 111 females) were included in the final analysis. Of these 266 patients, 179 patients were diagnosed to have TBTB. The age of the patients ranged from 13 to 91 years (mean age: 44.8 years) ( Table 1). The diagnostic yield of the different diagnostic methods is shown in Table 1. The details of the remaining 87 patients with non-TBTB are also provided in Table 1. The diagnostic yield of the Xpert MTB/RIF assay in different specimens obtained from TBTB patients is shown in Supplementary Table. As Table 1 shown, 87 cases were found to be other diagnosis among people suspected of having TBTB since in the differential diagnosis. Among the patients of TBTB, as for one of the initial treatment options in our patient, totally 89 patients underwent therapeutic bronchoscopy. Under bronchoscopy, if there was caseating necrosis or granular nodules or mucosal congestion and edema, cryotherapy via bronchoscope was performed; while if there was fibrous stenosis, balloon dilatation via bronchoscope was performed. None of the patients in this study received corticosteroid therapy for TBTB.\n\n\nDiagnostic Efficacy of Conventional Techniques and the Xpert MTB/RIF Assay in BALF for TBTB',
 'Diagnostic Efficacy of Conventional Techniques and the Xpert MTB/RIF Assay in BALF for TBTB\n\nThe diagnostic performance of the conventional techniques and the Xpert MTB/RIF assay in BALF for TBTB is shown in  Table 2). The sensitivity and NPV of the Xpert MTB/RIF assay in BALF were significantly higher than those of bronchial brush smear microscopy (χ 2 = 101.716, p < 0.001; χ 2 = 37.141, p < 0.001) ( Table 2). No difference in sensitivity was observed between the Xpert MTB/RIF assay and MTB culture in BALF (χ 2 = 0.372, p = 0.542) ( Table 2). \n\n\nComparison of Diagnostic Consistency of the Different Diagnostic Techniques\n\nThe diagnostic consistencies of the three different diagnostic techniques were compared (  Table 4). The tumorous and ulcerative subtypes were not included because our sample contained only three cases of these subtypes. The diagnostic rate of the Xpert MTB/RIF assay in BALF for the actively caseating subtype was significantly higher than that for the fibrostenotic subtype (χ 2 = 5.671, p = 0.030) ( Table 4). Moreover, the diagnostic rate of the Xpert MTB/RIF assay in BALF for the non-specific bronchitic subtype was significantly lower than that for the actively caseating subtype (χ 2 = 12.443, p < 0.001) or for the edematous-hyperemic subtype (χ 2 = 6.992, p = 0.008) ( Table 4).',
 'The diagnostic consistencies of the three different diagnostic techniques were compared (  Table 4). The tumorous and ulcerative subtypes were not included because our sample contained only three cases of these subtypes. The diagnostic rate of the Xpert MTB/RIF assay in BALF for the actively caseating subtype was significantly higher than that for the fibrostenotic subtype (χ 2 = 5.671, p = 0.030) ( Table 4). Moreover, the diagnostic rate of the Xpert MTB/RIF assay in BALF for the non-specific bronchitic subtype was significantly lower than that for the actively caseating subtype (χ 2 = 12.443, p < 0.001) or for the edematous-hyperemic subtype (χ 2 = 6.992, p = 0.008) ( Table 4). \n\n\nDISCUSSION\n\nThe diagnosis and treatment of TBTB are often delayed, resulting in the development of bronchial stenosis. Therefore, a timely and accurate diagnosis of TBTB is critical. Bronchoalveolar lavage is a less invasive and technically easy method for diagnosis. In our present study, we found that the diagnostic efficacy of the Xpert MTB/RIF assay in BALF was similar to that of the MTB culture in BALF but much faster for the initiation of the treatment.',

In [29]:
import re

def cleanup_text(text): 
    
    # remove new line characters
    new_text = re.sub("\n", " ", text)
    
    # remove double spaces
    new_text = re.sub("\s+", " ", new_text)
    
    return new_text

In [35]:
seperated_text.get('documents')

['Citation: Diagnostic Efficacy of Xpert MTB/RIF Assay in Bronchoalveolar Lavage Fluid for Tracheobronchial Tuberculosis: A Retrospective Analysis\nAugust 2021\n\nPiero Valentini \nJesica Mazza-Stalder \nQiao Liu \nSun Y \nZhang Q \nZhang Q \nLiu C \nZhang H Fu \nY Liu \nY \nHou G \nYue Sun \nInstitute of Respiratory Diseases\nThe First Hospital of China Medical University\nShenyangChina\n\n† \nQing Zhang \nDepartment of Endoscopy\nShenyang Chest Hospital\nShenyangChina\n\n† \nQin Zhang \nInstitute of Respiratory Diseases\nThe First Hospital of China Medical University\nShenyangChina\n\nChang Liu \nDepartment of Endoscopy\nShenyang Chest Hospital\nShenyangChina\n\nHong Zhang \nDepartment of Laboratory\nShenyang Chest Hospital\nShenyangChina\n\nYinghui Fu \nInstitute of Respiratory Diseases\nShenyang Chest Hospital\nShenyangChina\n\nYongyu Liu \nInstitute of Respiratory Diseases\nShenyang Chest Hospital\nShenyangChina\n\nGang Hou \nDepartment of Pulmonary and Critical Care Medicine\nCenter of Respiratory Medicine\nFriendship Hospital\nBeijingChina-Japan, China\n\nGraduate School of Peking Union Medical College\nChinese Academy of Medical Sciences\nPeking Union Medical College\nBeijingChina\n\nNational Center for Respiratory Medicine\nBeijingChina\n\nInstitute of Respiratory Medicine, Chinese Academy of Medical Sciences\nBeijingChina\n\nNational Clinical Research Center for Respiratory Diseases\nBeijingChina\n\n\nCentre Hospitalier Universitaire Vaudois (CHUV)\nUniversità Cattolica del Sacro Cuore\nItaly, Switzerland',
 'Hong Zhang \nDepartment of Laboratory\nShenyang Chest Hospital\nShenyangChina\n\nYinghui Fu \nInstitute of Respiratory Diseases\nShenyang Chest Hospital\nShenyangChina\n\nYongyu Liu \nInstitute of Respiratory Diseases\nShenyang Chest Hospital\nShenyangChina\n\nGang Hou \nDepartment of Pulmonary and Critical Care Medicine\nCenter of Respiratory Medicine\nFriendship Hospital\nBeijingChina-Japan, China\n\nGraduate School of Peking Union Medical College\nChinese Academy of Medical Sciences\nPeking Union Medical College\nBeijingChina\n\nNational Center for Respiratory Medicine\nBeijingChina\n\nInstitute of Respiratory Medicine, Chinese Academy of Medical Sciences\nBeijingChina\n\nNational Clinical Research Center for Respiratory Diseases\nBeijingChina\n\n\nCentre Hospitalier Universitaire Vaudois (CHUV)\nUniversità Cattolica del Sacro Cuore\nItaly, Switzerland\n\n\nNanjing Medical University\nChina\n\nCitation: Diagnostic Efficacy of Xpert MTB/RIF Assay in Bronchoalveolar Lavage Fluid for Tracheobronchial Tuberculosis: A Retrospective Analysis',
 'Frontiers in Medicine | www.frontiersin.org\n1682107August 202110.3389/fmed.2021.682107Received: 17 March 2021 Accepted: 12 July 2021ORIGINAL RESEARCH Edited by: Reviewed by: *Correspondence: Gang Hou hougangcmu@163.com Yongyu Liu L24315516@sina.com † These authors have contributed equally to this work Specialty section: This article was submitted to Pulmonary Medicine, a section of the journal Frontiers in Medicine (2021) Diagnostic Efficacy of Xpert MTB/RIF Assay in Bronchoalveolar Lavage Fluid for Tracheobronchial Tuberculosis: A Retrospective Analysis. Front. Med. 8:682107.Xpert MTB/RIFtracheobronchial tuberculosisbronchoalveolar lavagediagnosisMycobacterium tuberculosis\nBackground: The Xpert Mycobacterium tuberculosis/rifampin (MTB/RIF) assay has shown good diagnostic efficacy in brushing and biopsy tissue samples from patients with tracheobronchial tuberculosis (TBTB). However, its diagnostic value in bronchoalveolar lavage fluid (BALF) is still unclear. Therefore, the present retrospective study aimed to evaluate the diagnostic value of the Xpert MTB/RIF assay in BALF.Methods:The clinical data of 266 patients with suspected TBTB from January 2018 to October 2020 were pooled with complete details of bronchial brush and bronchoalveolar lavage samples. Smears of the bronchial brushings were stained with Auramine O stain to detect acid-fast bacilli (AFB), and BALF samples were used for culturing MTB with the BACTEC MGIT 960 system and the Xpert MTB/RIF assay. The diagnostic performance of these methods was assessed and compared.Results: A total of 266 patients suspected to have TBTB were enrolled in the final analysis. Of these patients, 179 patients were confirmed to have TBTB and 87 patients were non-TBTB. The sensitivity of the Xpert MTB/RIF assay in BALF (87.2%) was significantly higher than that of the brush smear for AFB (35.2%, p < 0.001). No significant difference was observed between the sensitivities of the Xpert MTB/RIF assay in BALF and MTB culture in BALF (87.2 vs. 84.9%, p = 0.542). The specificities of the Xpert MTB/RIF assay in BALF, MTB culture in BALF, and the bronchial brush smear were 97.7, 97.7, and 98.9%, respectively. The positive predictive value (PPV) and negative predictive value (NPV) of the Xpert MTB/RIF assay in BALF, MTB culture in BALF, and the bronchial brush smear were 98.7 and 78.7%, 98.7 and 75.9%, and 98.4 and 42.6%, respectively. Among the MTB culture-positive patients with TBTB detected by the Xpert assay, 27.0% (20/74) were identified to be resistant to RIF. Sun et al.Diagnostic Efficacy of Xpert MTB/RIFConclusions: The Xpert MTB/RIF assay in BALF enables a rapid and accurate diagnosis of TBTB and identification of RIF resistance, which is crucial for timely and proper treatment. Moreover, in patients with TBTB, BALF could be used as an alternative to bronchial brushing and biopsy tissues for the Xpert MTB/RIF assay.',
 "INTRODUCTION\n\nTuberculosis (TB) is considered to be the ninth leading cause of death worldwide, and it remains one of the major global public health issues (1). Tracheobronchial tuberculosis (TBTB) is a special form of TB and is defined as Mycobacterium tuberculosis (MTB) infection of the tracheobronchial tree with microbial and histopathological evidence, regardless of parenchymal involvement (2). TBTB has been reported in approximately 4.1-54.3% of patients with active pulmonary TB (3,4). Severe tracheobronchial stenosis caused by TBTB, which affects the patient's quality of life, was detected in 23.3% of patients with TBTB (5). The diagnosis of TBTB is, however, challenging because of its non-specific clinical manifestations, especially in the early stage, and unsatisfactory existing methods for acquiring microbial evidence. Thus, patients with TBTB often face a dilemma of delayed diagnosis and untimely treatment, which result in the occurrence and progression of severe tracheobronchial stenosis (6)(7)(8). Therefore, the rapid and accurate diagnosis of TBTB is crucial to minimize or prevent complications.",
 'The Xpert MTB/rifampin (MTB/RIF) assay (Cepheid, Sunnyvale, CA, USA) is an integrated semiautomated nucleic acid amplification test designed for rapid detection of the presence of MTB and mutations associated with RIF resistance within 2 h (9). Several previous studies have proved the diagnostic value of bronchoalveolar lavage fluid (BALF) for the Xpert MTB/RIF assay in adults and children with pulmonary TB (10)(11)(12). However, because TBTB is a special type of pulmonary TB, the efficacy of its diagnosis by using different methods varies from that for pulmonary TB and even among different subtypes of TBTB because of the different characteristics of exudation, proliferation, and necrosis. Our previous study (13) showed that the sensitivities of the Xpert MTB/RIF assay of bronchial brushing and biopsy samples from TBTB patients were 57. 4 and 63.9%, respectively, and the specificity for both types of samples was 100%; this proved that these results were superior to those of sputum smears, bronchial brush smears, and sputum culture. The yield of the Xpert MTB/RIF assay in bronchial brushings was significantly higher for the caseating or ulcerative subtypes than for the fibrostenotic or edematous-hyperemic subtypes (13). Bronchial biopsy and brushing samples may not be available for diagnosing bronchial fibrous stenosis and other conditions; however, in most TBTB cases, BALF is available and is a relatively less invasive and safer method. Hence, it is necessary to evaluate the diagnostic performance of the Xpert MTB/RIF assay in BALF for TBTB patients, and more specifically, to determine the diagnostic performance of the assay for different TBTB bronchoscopic subtypes. Therefore, we conducted this retrospective study to evaluate the efficacy of the Xpert MTB/RIF assay in BALF for the rapid diagnosis of TBTB.',
 'MATERIALS AND METHODS\n\n\nParticipants\n\nThis was a retrospective study conducted in the First Hospital of China Medical University and Shenyang Chest Hospital from Janurary 2018 to October 2020.\n\nA total of 266 suspected TBTB patients were enrolled in the study through the inpatient case registration system in the hospital information system. Inclusion criteria were as follows:\n\n(1) inpatient cases suspected to have TBTB who were registered in the hospital information system and were available for followup after 6 months and (2) patients who underwent bronchial brush and bronchoalveolar lavage sample collection. Brushing specimens were used for smears for acid-fast bacilli (AFB), while BALF samples were used for MTB culture and the Xpert MTB/RIF assay. Exclusion criteria were as follows: (1) patients without a definite diagnosis after discharge from the hospital and after 6 months of follow-up and (2) patients with obvious pulmonary involvement instead of TBTB alone.\n\nDefinition: TBTB was confirmed by the presence of a visible tracheobronchial lesion proximal to a segmental bronchus, with histological evidence from bronchial biopsy and/or microbiological tests (sputum smear or brushing smear or BALF was positive for AFB or MTB culture was positive) (5,14).',
 'Definition: TBTB was confirmed by the presence of a visible tracheobronchial lesion proximal to a segmental bronchus, with histological evidence from bronchial biopsy and/or microbiological tests (sputum smear or brushing smear or BALF was positive for AFB or MTB culture was positive) (5,14).\n\nClinical data of the patients were collected by two authors (YS and QinZ) from the medical databases of the hospitals. The study was approved by the Ethics Committee of China Medical University and Shenyang Chest Hospital. The ethics committee exempted obtaining informed consent from patients because of the retrospective nature of the study. Patient data were deidentified before data access and analysis.\n\n\nAFB Smear Microscopy\n\nThree bronchial brush smears were sent to the clinical microbiology laboratory for staining directly with rapid Auramine O fluorescent stain (AO stain, Ourchem, Sinopharm Chemical Reagent Co. Ltd., Shanghai, China) for detecting AFB by microscopy (15). Sputum for AFB detection was also collected during the hospitalization. The sample was considered AFB-positive if AFB was detected in at least one bronchial brush or sputum smear microscopy.\n\n\nBALF',
 'AFB Smear Microscopy\n\nThree bronchial brush smears were sent to the clinical microbiology laboratory for staining directly with rapid Auramine O fluorescent stain (AO stain, Ourchem, Sinopharm Chemical Reagent Co. Ltd., Shanghai, China) for detecting AFB by microscopy (15). Sputum for AFB detection was also collected during the hospitalization. The sample was considered AFB-positive if AFB was detected in at least one bronchial brush or sputum smear microscopy.\n\n\nBALF\n\nAll patients were assessed with an Olympus electronic bronchoscopy system (1T260, Tokyo, Japan). The bronchoscopy findings revealed that TBTB showed highly variable tracheobronchial appearance, and it was classified into seven subtypes according to pathological changes reported by Chung et al. (16): actively caseating, edematous-hyperemic, fibrostenotic, tumorous, granular, ulcerative, and non-specific bronchitis type. Bronchoalveolar lavage was obtained directly from the lesion location. The total amount of 37 • C saline, approximately 100 mL, was injected in equal doses, 20 mL in each dose, and finally, the lavage fluid was immediately recovered by vacuum suction (−100∼-150 mmHg).\n\n\nMTB Culture and Drug Sensitivity Test',
 'MTB Culture and Drug Sensitivity Test\n\nBALF specimens and sputum were processed using the BACTEC MGIT 960 rapid system (Becton Dickinson, Oxford, UK) for MTB culture (17). If the MTB culture was positive, the drug sensitivity was automatically tested through the BACTEC MGIT 960 SIRE kit (Becton Dickinson) (17).\n\n\nXpert MTB/RIF Assay\n\nFive milliliters of BALF specimen were taken and mixed evenly with a sample reagent buffer (SR) (containing sodium hydroxide and isopropanol) in the ratio of 2:1. The mixture was left to stand at room temperature for 15 min and then transferred to the MTB/RIF detection kit (Cepheid, USA). The reaction box was placed in the Gene Xpert instrument (Cepheid) for detection. The Xpert MTB/RIF assay has been designed to detect MTB and also mutations that confer resistance to rifampicin by using three specific primers and five unique molecular probes that target the 81-bp core region of the bacterial RNA polymerase β subunit (rpoB) gene (18)(19)(20).\n\n\nStatistical Analysis',
 'Five milliliters of BALF specimen were taken and mixed evenly with a sample reagent buffer (SR) (containing sodium hydroxide and isopropanol) in the ratio of 2:1. The mixture was left to stand at room temperature for 15 min and then transferred to the MTB/RIF detection kit (Cepheid, USA). The reaction box was placed in the Gene Xpert instrument (Cepheid) for detection. The Xpert MTB/RIF assay has been designed to detect MTB and also mutations that confer resistance to rifampicin by using three specific primers and five unique molecular probes that target the 81-bp core region of the bacterial RNA polymerase β subunit (rpoB) gene (18)(19)(20).\n\n\nStatistical Analysis\n\nIBM SPSS version 20.0 software (SPSS Inc., Chicago, IL, USA) was used for the statistical analysis. The sensitivity, specificity, positive predictive value (PPV), and negative predictive value (NPV) of the different diagnostic methods were calculated with two-sided 95% confidence intervals (CIs). The diagnostic performance of the different diagnostic methods for various bronchial subtypes was compared with chi-square tests. A P-value of <0.05 was considered to be statistically significant.\n\n\nRESULTS\n\n\nPatient Characteristics',
 'RESULTS\n\n\nPatient Characteristics\n\nA total of 266 patients (155 males and 111 females) were included in the final analysis. Of these 266 patients, 179 patients were diagnosed to have TBTB. The age of the patients ranged from 13 to 91 years (mean age: 44.8 years) ( Table 1). The diagnostic yield of the different diagnostic methods is shown in Table 1. The details of the remaining 87 patients with non-TBTB are also provided in Table 1. The diagnostic yield of the Xpert MTB/RIF assay in different specimens obtained from TBTB patients is shown in Supplementary Table. As Table 1 shown, 87 cases were found to be other diagnosis among people suspected of having TBTB since in the differential diagnosis. Among the patients of TBTB, as for one of the initial treatment options in our patient, totally 89 patients underwent therapeutic bronchoscopy. Under bronchoscopy, if there was caseating necrosis or granular nodules or mucosal congestion and edema, cryotherapy via bronchoscope was performed; while if there was fibrous stenosis, balloon dilatation via bronchoscope was performed. None of the patients in this study received corticosteroid therapy for TBTB.\n\n\nDiagnostic Efficacy of Conventional Techniques and the Xpert MTB/RIF Assay in BALF for TBTB',
 'Diagnostic Efficacy of Conventional Techniques and the Xpert MTB/RIF Assay in BALF for TBTB\n\nThe diagnostic performance of the conventional techniques and the Xpert MTB/RIF assay in BALF for TBTB is shown in  Table 2). The sensitivity and NPV of the Xpert MTB/RIF assay in BALF were significantly higher than those of bronchial brush smear microscopy (χ 2 = 101.716, p < 0.001; χ 2 = 37.141, p < 0.001) ( Table 2). No difference in sensitivity was observed between the Xpert MTB/RIF assay and MTB culture in BALF (χ 2 = 0.372, p = 0.542) ( Table 2). \n\n\nComparison of Diagnostic Consistency of the Different Diagnostic Techniques\n\nThe diagnostic consistencies of the three different diagnostic techniques were compared (  Table 4). The tumorous and ulcerative subtypes were not included because our sample contained only three cases of these subtypes. The diagnostic rate of the Xpert MTB/RIF assay in BALF for the actively caseating subtype was significantly higher than that for the fibrostenotic subtype (χ 2 = 5.671, p = 0.030) ( Table 4). Moreover, the diagnostic rate of the Xpert MTB/RIF assay in BALF for the non-specific bronchitic subtype was significantly lower than that for the actively caseating subtype (χ 2 = 12.443, p < 0.001) or for the edematous-hyperemic subtype (χ 2 = 6.992, p = 0.008) ( Table 4).',
 'The diagnostic consistencies of the three different diagnostic techniques were compared (  Table 4). The tumorous and ulcerative subtypes were not included because our sample contained only three cases of these subtypes. The diagnostic rate of the Xpert MTB/RIF assay in BALF for the actively caseating subtype was significantly higher than that for the fibrostenotic subtype (χ 2 = 5.671, p = 0.030) ( Table 4). Moreover, the diagnostic rate of the Xpert MTB/RIF assay in BALF for the non-specific bronchitic subtype was significantly lower than that for the actively caseating subtype (χ 2 = 12.443, p < 0.001) or for the edematous-hyperemic subtype (χ 2 = 6.992, p = 0.008) ( Table 4). \n\n\nDISCUSSION\n\nThe diagnosis and treatment of TBTB are often delayed, resulting in the development of bronchial stenosis. Therefore, a timely and accurate diagnosis of TBTB is critical. Bronchoalveolar lavage is a less invasive and technically easy method for diagnosis. In our present study, we found that the diagnostic efficacy of the Xpert MTB/RIF assay in BALF was similar to that of the MTB culture in BALF but much faster for the initiation of the treatment.',

In [33]:
fulltext_examples = [cleanup_text(st) for st in seperated_text.get('documents')]

In [36]:
fulltext_examples

['Citation: Diagnostic Efficacy of Xpert MTB/RIF Assay in Bronchoalveolar Lavage Fluid for Tracheobronchial Tuberculosis: A Retrospective Analysis August 2021 Piero Valentini Jesica Mazza-Stalder Qiao Liu Sun Y Zhang Q Zhang Q Liu C Zhang H Fu Y Liu Y Hou G Yue Sun Institute of Respiratory Diseases The First Hospital of China Medical University ShenyangChina † Qing Zhang Department of Endoscopy Shenyang Chest Hospital ShenyangChina † Qin Zhang Institute of Respiratory Diseases The First Hospital of China Medical University ShenyangChina Chang Liu Department of Endoscopy Shenyang Chest Hospital ShenyangChina Hong Zhang Department of Laboratory Shenyang Chest Hospital ShenyangChina Yinghui Fu Institute of Respiratory Diseases Shenyang Chest Hospital ShenyangChina Yongyu Liu Institute of Respiratory Diseases Shenyang Chest Hospital ShenyangChina Gang Hou Department of Pulmonary and Critical Care Medicine Center of Respiratory Medicine Friendship Hospital BeijingChina-Japan, China Graduate School of Peking Union Medical College Chinese Academy of Medical Sciences Peking Union Medical College BeijingChina National Center for Respiratory Medicine BeijingChina Institute of Respiratory Medicine, Chinese Academy of Medical Sciences BeijingChina National Clinical Research Center for Respiratory Diseases BeijingChina Centre Hospitalier Universitaire Vaudois (CHUV) Università Cattolica del Sacro Cuore Italy, Switzerland',
 'Hong Zhang Department of Laboratory Shenyang Chest Hospital ShenyangChina Yinghui Fu Institute of Respiratory Diseases Shenyang Chest Hospital ShenyangChina Yongyu Liu Institute of Respiratory Diseases Shenyang Chest Hospital ShenyangChina Gang Hou Department of Pulmonary and Critical Care Medicine Center of Respiratory Medicine Friendship Hospital BeijingChina-Japan, China Graduate School of Peking Union Medical College Chinese Academy of Medical Sciences Peking Union Medical College BeijingChina National Center for Respiratory Medicine BeijingChina Institute of Respiratory Medicine, Chinese Academy of Medical Sciences BeijingChina National Clinical Research Center for Respiratory Diseases BeijingChina Centre Hospitalier Universitaire Vaudois (CHUV) Università Cattolica del Sacro Cuore Italy, Switzerland Nanjing Medical University China Citation: Diagnostic Efficacy of Xpert MTB/RIF Assay in Bronchoalveolar Lavage Fluid for Tracheobronchial Tuberculosis: A Retrospective Analysis',
 'Frontiers in Medicine | www.frontiersin.org 1682107August 202110.3389/fmed.2021.682107Received: 17 March 2021 Accepted: 12 July 2021ORIGINAL RESEARCH Edited by: Reviewed by: *Correspondence: Gang Hou hougangcmu@163.com Yongyu Liu L24315516@sina.com † These authors have contributed equally to this work Specialty section: This article was submitted to Pulmonary Medicine, a section of the journal Frontiers in Medicine (2021) Diagnostic Efficacy of Xpert MTB/RIF Assay in Bronchoalveolar Lavage Fluid for Tracheobronchial Tuberculosis: A Retrospective Analysis. Front. Med. 8:682107.Xpert MTB/RIFtracheobronchial tuberculosisbronchoalveolar lavagediagnosisMycobacterium tuberculosis Background: The Xpert Mycobacterium tuberculosis/rifampin (MTB/RIF) assay has shown good diagnostic efficacy in brushing and biopsy tissue samples from patients with tracheobronchial tuberculosis (TBTB). However, its diagnostic value in bronchoalveolar lavage fluid (BALF) is still unclear. Therefore, the present retrospective study aimed to evaluate the diagnostic value of the Xpert MTB/RIF assay in BALF.Methods:The clinical data of 266 patients with suspected TBTB from January 2018 to October 2020 were pooled with complete details of bronchial brush and bronchoalveolar lavage samples. Smears of the bronchial brushings were stained with Auramine O stain to detect acid-fast bacilli (AFB), and BALF samples were used for culturing MTB with the BACTEC MGIT 960 system and the Xpert MTB/RIF assay. The diagnostic performance of these methods was assessed and compared.Results: A total of 266 patients suspected to have TBTB were enrolled in the final analysis. Of these patients, 179 patients were confirmed to have TBTB and 87 patients were non-TBTB. The sensitivity of the Xpert MTB/RIF assay in BALF (87.2%) was significantly higher than that of the brush smear for AFB (35.2%, p < 0.001). No significant difference was observed between the sensitivities of the Xpert MTB/RIF assay in BALF and MTB culture in BALF (87.2 vs. 84.9%, p = 0.542). The specificities of the Xpert MTB/RIF assay in BALF, MTB culture in BALF, and the bronchial brush smear were 97.7, 97.7, and 98.9%, respectively. The positive predictive value (PPV) and negative predictive value (NPV) of the Xpert MTB/RIF assay in BALF, MTB culture in BALF, and the bronchial brush smear were 98.7 and 78.7%, 98.7 and 75.9%, and 98.4 and 42.6%, respectively. Among the MTB culture-positive patients with TBTB detected by the Xpert assay, 27.0% (20/74) were identified to be resistant to RIF. Sun et al.Diagnostic Efficacy of Xpert MTB/RIFConclusions: The Xpert MTB/RIF assay in BALF enables a rapid and accurate diagnosis of TBTB and identification of RIF resistance, which is crucial for timely and proper treatment. Moreover, in patients with TBTB, BALF could be used as an alternative to bronchial brushing and biopsy tissues for the Xpert MTB/RIF assay.',
 "INTRODUCTION Tuberculosis (TB) is considered to be the ninth leading cause of death worldwide, and it remains one of the major global public health issues (1). Tracheobronchial tuberculosis (TBTB) is a special form of TB and is defined as Mycobacterium tuberculosis (MTB) infection of the tracheobronchial tree with microbial and histopathological evidence, regardless of parenchymal involvement (2). TBTB has been reported in approximately 4.1-54.3% of patients with active pulmonary TB (3,4). Severe tracheobronchial stenosis caused by TBTB, which affects the patient's quality of life, was detected in 23.3% of patients with TBTB (5). The diagnosis of TBTB is, however, challenging because of its non-specific clinical manifestations, especially in the early stage, and unsatisfactory existing methods for acquiring microbial evidence. Thus, patients with TBTB often face a dilemma of delayed diagnosis and untimely treatment, which result in the occurrence and progression of severe tracheobronchial stenosis (6)(7)(8). Therefore, the rapid and accurate diagnosis of TBTB is crucial to minimize or prevent complications.",
 'The Xpert MTB/rifampin (MTB/RIF) assay (Cepheid, Sunnyvale, CA, USA) is an integrated semiautomated nucleic acid amplification test designed for rapid detection of the presence of MTB and mutations associated with RIF resistance within 2 h (9). Several previous studies have proved the diagnostic value of bronchoalveolar lavage fluid (BALF) for the Xpert MTB/RIF assay in adults and children with pulmonary TB (10)(11)(12). However, because TBTB is a special type of pulmonary TB, the efficacy of its diagnosis by using different methods varies from that for pulmonary TB and even among different subtypes of TBTB because of the different characteristics of exudation, proliferation, and necrosis. Our previous study (13) showed that the sensitivities of the Xpert MTB/RIF assay of bronchial brushing and biopsy samples from TBTB patients were 57. 4 and 63.9%, respectively, and the specificity for both types of samples was 100%; this proved that these results were superior to those of sputum smears, bronchial brush smears, and sputum culture. The yield of the Xpert MTB/RIF assay in bronchial brushings was significantly higher for the caseating or ulcerative subtypes than for the fibrostenotic or edematous-hyperemic subtypes (13). Bronchial biopsy and brushing samples may not be available for diagnosing bronchial fibrous stenosis and other conditions; however, in most TBTB cases, BALF is available and is a relatively less invasive and safer method. Hence, it is necessary to evaluate the diagnostic performance of the Xpert MTB/RIF assay in BALF for TBTB patients, and more specifically, to determine the diagnostic performance of the assay for different TBTB bronchoscopic subtypes. Therefore, we conducted this retrospective study to evaluate the efficacy of the Xpert MTB/RIF assay in BALF for the rapid diagnosis of TBTB.',
 'MATERIALS AND METHODS Participants This was a retrospective study conducted in the First Hospital of China Medical University and Shenyang Chest Hospital from Janurary 2018 to October 2020. A total of 266 suspected TBTB patients were enrolled in the study through the inpatient case registration system in the hospital information system. Inclusion criteria were as follows: (1) inpatient cases suspected to have TBTB who were registered in the hospital information system and were available for followup after 6 months and (2) patients who underwent bronchial brush and bronchoalveolar lavage sample collection. Brushing specimens were used for smears for acid-fast bacilli (AFB), while BALF samples were used for MTB culture and the Xpert MTB/RIF assay. Exclusion criteria were as follows: (1) patients without a definite diagnosis after discharge from the hospital and after 6 months of follow-up and (2) patients with obvious pulmonary involvement instead of TBTB alone. Definition: TBTB was confirmed by the presence of a visible tracheobronchial lesion proximal to a segmental bronchus, with histological evidence from bronchial biopsy and/or microbiological tests (sputum smear or brushing smear or BALF was positive for AFB or MTB culture was positive) (5,14).',
 'Definition: TBTB was confirmed by the presence of a visible tracheobronchial lesion proximal to a segmental bronchus, with histological evidence from bronchial biopsy and/or microbiological tests (sputum smear or brushing smear or BALF was positive for AFB or MTB culture was positive) (5,14). Clinical data of the patients were collected by two authors (YS and QinZ) from the medical databases of the hospitals. The study was approved by the Ethics Committee of China Medical University and Shenyang Chest Hospital. The ethics committee exempted obtaining informed consent from patients because of the retrospective nature of the study. Patient data were deidentified before data access and analysis. AFB Smear Microscopy Three bronchial brush smears were sent to the clinical microbiology laboratory for staining directly with rapid Auramine O fluorescent stain (AO stain, Ourchem, Sinopharm Chemical Reagent Co. Ltd., Shanghai, China) for detecting AFB by microscopy (15). Sputum for AFB detection was also collected during the hospitalization. The sample was considered AFB-positive if AFB was detected in at least one bronchial brush or sputum smear microscopy. BALF',
 'AFB Smear Microscopy Three bronchial brush smears were sent to the clinical microbiology laboratory for staining directly with rapid Auramine O fluorescent stain (AO stain, Ourchem, Sinopharm Chemical Reagent Co. Ltd., Shanghai, China) for detecting AFB by microscopy (15). Sputum for AFB detection was also collected during the hospitalization. The sample was considered AFB-positive if AFB was detected in at least one bronchial brush or sputum smear microscopy. BALF All patients were assessed with an Olympus electronic bronchoscopy system (1T260, Tokyo, Japan). The bronchoscopy findings revealed that TBTB showed highly variable tracheobronchial appearance, and it was classified into seven subtypes according to pathological changes reported by Chung et al. (16): actively caseating, edematous-hyperemic, fibrostenotic, tumorous, granular, ulcerative, and non-specific bronchitis type. Bronchoalveolar lavage was obtained directly from the lesion location. The total amount of 37 • C saline, approximately 100 mL, was injected in equal doses, 20 mL in each dose, and finally, the lavage fluid was immediately recovered by vacuum suction (−100∼-150 mmHg). MTB Culture and Drug Sensitivity Test',
 'MTB Culture and Drug Sensitivity Test BALF specimens and sputum were processed using the BACTEC MGIT 960 rapid system (Becton Dickinson, Oxford, UK) for MTB culture (17). If the MTB culture was positive, the drug sensitivity was automatically tested through the BACTEC MGIT 960 SIRE kit (Becton Dickinson) (17). Xpert MTB/RIF Assay Five milliliters of BALF specimen were taken and mixed evenly with a sample reagent buffer (SR) (containing sodium hydroxide and isopropanol) in the ratio of 2:1. The mixture was left to stand at room temperature for 15 min and then transferred to the MTB/RIF detection kit (Cepheid, USA). The reaction box was placed in the Gene Xpert instrument (Cepheid) for detection. The Xpert MTB/RIF assay has been designed to detect MTB and also mutations that confer resistance to rifampicin by using three specific primers and five unique molecular probes that target the 81-bp core region of the bacterial RNA polymerase β subunit (rpoB) gene (18)(19)(20). Statistical Analysis',
 'Five milliliters of BALF specimen were taken and mixed evenly with a sample reagent buffer (SR) (containing sodium hydroxide and isopropanol) in the ratio of 2:1. The mixture was left to stand at room temperature for 15 min and then transferred to the MTB/RIF detection kit (Cepheid, USA). The reaction box was placed in the Gene Xpert instrument (Cepheid) for detection. The Xpert MTB/RIF assay has been designed to detect MTB and also mutations that confer resistance to rifampicin by using three specific primers and five unique molecular probes that target the 81-bp core region of the bacterial RNA polymerase β subunit (rpoB) gene (18)(19)(20). Statistical Analysis IBM SPSS version 20.0 software (SPSS Inc., Chicago, IL, USA) was used for the statistical analysis. The sensitivity, specificity, positive predictive value (PPV), and negative predictive value (NPV) of the different diagnostic methods were calculated with two-sided 95% confidence intervals (CIs). The diagnostic performance of the different diagnostic methods for various bronchial subtypes was compared with chi-square tests. A P-value of <0.05 was considered to be statistically significant. RESULTS Patient Characteristics',
 'RESULTS Patient Characteristics A total of 266 patients (155 males and 111 females) were included in the final analysis. Of these 266 patients, 179 patients were diagnosed to have TBTB. The age of the patients ranged from 13 to 91 years (mean age: 44.8 years) ( Table 1). The diagnostic yield of the different diagnostic methods is shown in Table 1. The details of the remaining 87 patients with non-TBTB are also provided in Table 1. The diagnostic yield of the Xpert MTB/RIF assay in different specimens obtained from TBTB patients is shown in Supplementary Table. As Table 1 shown, 87 cases were found to be other diagnosis among people suspected of having TBTB since in the differential diagnosis. Among the patients of TBTB, as for one of the initial treatment options in our patient, totally 89 patients underwent therapeutic bronchoscopy. Under bronchoscopy, if there was caseating necrosis or granular nodules or mucosal congestion and edema, cryotherapy via bronchoscope was performed; while if there was fibrous stenosis, balloon dilatation via bronchoscope was performed. None of the patients in this study received corticosteroid therapy for TBTB. Diagnostic Efficacy of Conventional Techniques and the Xpert MTB/RIF Assay in BALF for TBTB',
 'Diagnostic Efficacy of Conventional Techniques and the Xpert MTB/RIF Assay in BALF for TBTB The diagnostic performance of the conventional techniques and the Xpert MTB/RIF assay in BALF for TBTB is shown in Table 2). The sensitivity and NPV of the Xpert MTB/RIF assay in BALF were significantly higher than those of bronchial brush smear microscopy (χ 2 = 101.716, p < 0.001; χ 2 = 37.141, p < 0.001) ( Table 2). No difference in sensitivity was observed between the Xpert MTB/RIF assay and MTB culture in BALF (χ 2 = 0.372, p = 0.542) ( Table 2). Comparison of Diagnostic Consistency of the Different Diagnostic Techniques The diagnostic consistencies of the three different diagnostic techniques were compared ( Table 4). The tumorous and ulcerative subtypes were not included because our sample contained only three cases of these subtypes. The diagnostic rate of the Xpert MTB/RIF assay in BALF for the actively caseating subtype was significantly higher than that for the fibrostenotic subtype (χ 2 = 5.671, p = 0.030) ( Table 4). Moreover, the diagnostic rate of the Xpert MTB/RIF assay in BALF for the non-specific bronchitic subtype was significantly lower than that for the actively caseating subtype (χ 2 = 12.443, p < 0.001) or for the edematous-hyperemic subtype (χ 2 = 6.992, p = 0.008) ( Table 4).',
 'The diagnostic consistencies of the three different diagnostic techniques were compared ( Table 4). The tumorous and ulcerative subtypes were not included because our sample contained only three cases of these subtypes. The diagnostic rate of the Xpert MTB/RIF assay in BALF for the actively caseating subtype was significantly higher than that for the fibrostenotic subtype (χ 2 = 5.671, p = 0.030) ( Table 4). Moreover, the diagnostic rate of the Xpert MTB/RIF assay in BALF for the non-specific bronchitic subtype was significantly lower than that for the actively caseating subtype (χ 2 = 12.443, p < 0.001) or for the edematous-hyperemic subtype (χ 2 = 6.992, p = 0.008) ( Table 4). DISCUSSION The diagnosis and treatment of TBTB are often delayed, resulting in the development of bronchial stenosis. Therefore, a timely and accurate diagnosis of TBTB is critical. Bronchoalveolar lavage is a less invasive and technically easy method for diagnosis. In our present study, we found that the diagnostic efficacy of the Xpert MTB/RIF assay in BALF was similar to that of the MTB culture in BALF but much faster for the initiation of the treatment.',

In [31]:
fulltext_example = cleanup_text(seperated_text.get('documents')[0])

In [37]:
# Use text_splitter to split documents
# Use Documents package to format text

docs = [Document(page_content=t) for t in fulltext_examples]

embedding_function = SentenceTransformerEmbeddings(model_name="t5-large")

vectordb = Chroma.from_documents(docs, embedding_function)

chain = load_summarize_chain(llm, chain_type="map_reduce")

chain.run(docs)

2023-07-23 22:41:05 ip-172-31-64-95 sentence_transformers.SentenceTransformer[29969] INFO Load pretrained SentenceTransformer: t5-large

2023-07-23 22:41:05 ip-172-31-64-95 sentence_transformers.SentenceTransformer[29969] WARNING No sentence-transformers model found with name /home/ubuntu/.cache/torch/sentence_transformers/t5-large. Creating a new one with MEAN pooling.
2023-07-23 22:41:09 ip-172-31-64-95 sentence_transformers.SentenceTransformer[29969] INFO Use pytorch device: cpu
2023-07-23 22:41:09 ip-172-31-64-95 chromadb.telemetry.posthog[29969] INFO Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
2023-07-23 22:41:09 ip-172-31-64-95 clickhouse_connect.driver.ctypes[29969] INFO Successfully imported ClickHouse Connect C data optimizations
2023-07-23 22:41:09 ip-172-31-64-95 clickhouse_connect.json_impl[29969] INFO Using python library for writing JSON byte strings

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
2023-07-23 22:43:52 ip-172-31-64-95 openai[29969] INFO error_code=insufficient_quota error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False
2023-07-23 22:43:52 ip-172-31-64-95 langchain.llms.base[29969] WARNING Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
2023-07-23 22:43:56 ip-172-31-64-95 openai[29969] INFO error_code=insufficient_quota error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False
2023-07-23 22:43:56 ip-172-31-64-95 langchain.llms.base[29969] WARNING Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
2023-07-23 22:44:00 ip-172-31-64-95 openai[29969] INFO error_code=insufficient_quota error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False
2023-07-23 22:44:00 ip-172-31-64-95 langchain.llms.base[29969] WARNING Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
2023-07-23 22:44:05 ip-172-31-64-95 openai[29969] INFO error_code=insufficient_quota error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False
2023-07-23 22:44:05 ip-172-31-64-95 langchain.llms.base[29969] WARNING Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 8.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
2023-07-23 22:44:13 ip-172-31-64-95 openai[29969] INFO error_code=insufficient_quota error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False
2023-07-23 22:44:13 ip-172-31-64-95 langchain.llms.base[29969] WARNING Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 10.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..
2023-07-23 22:44:24 ip-172-31-64-95 openai[29969] INFO error_code=insufficient_quota error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False

RateLimitError: You exceeded your current quota, please check your plan and billing details.

In [22]:
# Query to extract full text from postgres
def requested_papers(courpusId_list, summary=False):
    if summary:
        table_name = "abstracts_encodings"
    else:
        table_name = "fulltext"

    client_request = text(
        f"""
        SELECT empty, corpusId, text, id FROM {table_name} """
    )

    with engine.connect() as conn:
        query = conn.execute(client_request).filter(
            fulltext.corpusid.in_(corpusID_list)
        )

    solution_papers = pd.DataFrame(query.fetchall())
    
    return solution_papers

In [ ]:
# Huggingface transformer abstract summarization T5 and LED
def hugging_face_summarization(model, tokenizer, dataset):
    abstract_holder = []
    for i in dataset["abstracts"]:
        tokenized_abstract = tokenizer(
            ["Summarize" + i], truncation=True, padding=True, max_length=True
        )
        
        output_encodings = model.genertae(
            tokenized_abstract.input_ids,
            num_beams=4,
            top_k=10,
            top_p=80,
            no_repeat_ngram_size=3,
            max_length=100,
            min_length=50,
        )
        abstract_summary = [
            tokenizer.decode(
                w, skip_special_tokens=True, clean_up_tokenization_spaces=True
            )
            for w in output_encodings
        ]
        abstract_holder.append(abstract_summary)
    return abstract_holder

In [27]:
user_input = "Phrenic nerve palsy"
input_string = " & ".join(user_input.split(" "))

sql = f"""
SELECT
    attributes.title,
    abstract, 
    corpusid             
FROM abstract_encodings_test4
JOIN attributes using (corpusid)
WHERE ts_left_750 @@ websearch_to_tsquery('english','{input_string}')
order by attributes.referencecount desc, attributes.publicationdate, attributes.citationcount desc
limit 5

"""
with engine.connect() as conn:
    query = conn.execute(sqlalchemy.text(sql))

df = pd.DataFrame(query.fetchall())
df

,title,abstract,corpusid
0,Role of reinnervation in the management of rec...,Purpose of review To present the current state...,30566805
1,Unilateral cranial and phrenic nerve involveme...,A 49‐year‐old woman developed acute left facia...,19507676
2,Seronegative neuromyelitis optica presenting w...,Context: Dyspnea has rarely been reported as a...,3585446
3,Bilateral brachial plexus block in a patient w...,Abstract Rationale: Bilateral brachial plexus ...,220971384
4,Phrenic Nerve Conduction in Children,A study was undertaken in order to establish t...,38267212

#### Question & Answer

In [ ]:
from langchain.vectorstores import Chroma
from langchain.embeddings import OpenAIEmbeddings

qa = VectorDBQA.from_chain_type(
    llm=OpenAI(), chain_type="map_reduce", vectorstore=lang_collect
)